import type { jsPDF } from 'jspdf';
import { amountInWords, formatDate } from '../services/calculations';
import type { CrmSettings, Customer, Quotation } from '../types/domain';

interface QuotationPdfInput { quote: Quotation; customer: Customer; settings: CrmSettings; copyType: 'customer'|'internal'; }

const BLUE:[number,number,number]=[6,78,145];
const clean=(value:unknown)=>String(value??'-').replace(/[×]/g,'x').replace(/[·]/g,' - ').replace(/[–—]/g,'-').replace(/[’]/g,"'").replace(/[₹]/g,'INR ').replace(/[^\x20-\x7E]/g,' ').replace(/\s+/g,' ').trim();
const money=(value:number)=>`INR ${new Intl.NumberFormat('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2}).format(value||0)}`;
const wrap=(doc:jsPDF,text:string,width:number)=>doc.splitTextToSize(clean(text),width) as string[];

function lines(doc:jsPDF,text:string|string[],x:number,y:number,width:number,size=9,style:'normal'|'bold'|'italic'='normal',lineHeight=4){
  const rows=Array.isArray(text)?text:wrap(doc,text,width); doc.setFont('times',style); doc.setFontSize(size); rows.forEach((row,index)=>doc.text(clean(row),x,y+index*lineHeight)); return y+rows.length*lineHeight;
}

async function imageData(url:string){const response=await fetch(url);if(!response.ok)return null;const blob=await response.blob();return await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error);reader.onload=()=>resolve(String(reader.result));reader.readAsDataURL(blob);});}

function header(doc:jsPDF,input:QuotationPdfInput,logo:string|null){const{company}=input.settings;doc.setTextColor(...BLUE);doc.setFont('helvetica','bold');doc.setFontSize(12);doc.text(`G.S.T. No. ${clean(company.gstin)}`,12,13);doc.setFontSize(8.4);doc.text('ELECTRICAL, MECHANICAL & CIVIL CONTRACTOR',12,21);doc.setDrawColor(...BLUE);doc.setLineWidth(1);doc.line(12,24,127,24);if(logo)doc.addImage(logo,'PNG',139,7,58,19,undefined,'NONE');else{doc.setFontSize(14);doc.text(clean(company.tradeName),197,18,{align:'right'});}doc.setTextColor(0,0,0);}
function footer(doc:jsPDF,input:QuotationPdfInput){const{company}=input.settings;doc.setDrawColor(...BLUE);doc.setLineWidth(1);doc.line(8,277,202,277);doc.setTextColor(...BLUE);doc.setFont('helvetica','bold');doc.setFontSize(7.3);doc.text(clean(company.address),105,284,{align:'center'});doc.text(clean(`(M) ${[company.mobilePrimary,company.mobileSecondary].filter(Boolean).join(' / ')}   E-mail : ${company.email}`),105,289,{align:'center'});doc.setTextColor(0,0,0);}
function sectionRule(doc:jsPDF,y:number){doc.setDrawColor(145,145,145);doc.setLineWidth(.5);doc.line(15,y,195,y);}

function supplyTable(doc:jsPDF,input:QuotationPdfInput,top:number){const{quote}=input;const x=15;const widths=[12,82,22,20,26,28];const pos=[x];widths.forEach(w=>pos.push((pos.at(-1)??x)+w));const headerH=9;const bodyH=17;doc.setDrawColor(30,30,30);doc.setLineWidth(.25);doc.rect(x,top,190,headerH+bodyH);doc.line(x,top+headerH,205,top+headerH);pos.slice(1,-1).forEach(px=>doc.line(px,top,px,top+headerH+bodyH));const heads=['Sr. No','Description of Goods','HSN Code','Qty','Unit Rate','Amount'];doc.setFont('times','bold');doc.setFontSize(7.5);heads.forEach((h,i)=>doc.text(h,pos[i]!+widths[i]!/2,top+5.7,{align:'center'}));doc.setFont('times','normal');doc.setFontSize(8.5);doc.text('1',pos[0]!+widths[0]!/2,top+16,{align:'center'});doc.setFont('times','bold');doc.text('Rooftop Solar System',pos[1]!+2,top+14);doc.setFont('times','normal');doc.text(clean(`under ${quote.scheme}`),pos[1]!+2,top+19);doc.text('-',pos[2]!+widths[2]!/2,top+16,{align:'center'});doc.text(`${quote.dcCapacityKw.toFixed(2)} kW`,pos[3]!+widths[3]!/2,top+16,{align:'center'});doc.text(money(quote.grandTotal),pos[4]!+widths[4]!-1.5,top+16,{align:'right'});doc.setFont('times','bold');doc.text(money(quote.grandTotal),pos[5]!+widths[5]!-1.5,top+16,{align:'right'});return top+headerH+bodyH;}

function subsidyTable(doc:jsPDF,input:QuotationPdfInput,top:number){const{quote}=input;const reference=quote.subsidy.referenceLines?.length?quote.subsidy.referenceLines:[{label:'Central Subsidy (Up to 2 kW)',amount:30000},{label:'Central Subsidy (Above 2 kW)',amount:18000},{label:'State Subsidy (Above 2 kW)',amount:30000},{label:'Agreement Charges',amount:350}];const rows:Array<[string,string,string]>=[...reference.map((line,index)=>[String(index+1),line.label,money(line.amount)] as [string,string,string]),['','Total Informational Subsidy',money(quote.subsidy.total||78000)]];const x=15;const widths=[16,92,38];const pos=[x];widths.forEach(w=>pos.push((pos.at(-1)??x)+w));const rowH=6.4;doc.setLineWidth(.25);doc.rect(x,top,146,rowH*(rows.length+1));pos.slice(1,-1).forEach(px=>doc.line(px,top,px,top+rowH*(rows.length+1)));for(let i=1;i<=rows.length;i++)doc.line(x,top+rowH*i,x+146,top+rowH*i);doc.setFont('times','bold');doc.setFontSize(7.7);['Sr. No','Description','Amount'].forEach((h,i)=>doc.text(h,pos[i]!+widths[i]!/2,top+4.4,{align:'center'}));rows.forEach((row,index)=>{const y=top+rowH*(index+1)+4.4;doc.setFont('times',index===rows.length-1?'bold':'normal');doc.text(row[0],pos[0]!+widths[0]!/2,y,{align:'center'});doc.text(row[1],pos[1]!+2,y);doc.text(row[2],pos[2]!+widths[2]!-1.5,y,{align:'right'});});return top+rowH*(rows.length+1);}

function drawPageOne(doc:jsPDF,input:QuotationPdfInput,logo:string|null){const{quote,customer,settings}=input;const{company}=settings;header(doc,input,logo);doc.setFont('times','bold');doc.setFontSize(10);doc.text('Quotation No.:',15,34);doc.setFont('times','normal');doc.text(clean(quote.quoteNo),43,34);doc.setFont('times','bold');doc.text('Date:',143,34);doc.setFont('times','normal');doc.text(formatDate(quote.createdAt),157,34);doc.setFont('times','bold');doc.setFontSize(14);doc.text('QUOTATION',18,44);doc.setLineWidth(.35);doc.line(18,45,48,45);let y=52;doc.setFont('times','bold');doc.setFontSize(10);doc.text('From,',15,y);y+=5;doc.setFontSize(11.5);doc.text(clean(company.legalName),15,y);y+=4.5;y=lines(doc,company.address,15,y,165,9.2,'normal',4);y=lines(doc,`Mobile: +91 ${company.mobilePrimary}`,15,y,165,9.2,'normal',4);y=lines(doc,`GSTIN: ${company.gstin} | PAN: ${company.pan}`,15,y,165,9.2,'normal',4);doc.setFont('times','bold');doc.setFontSize(10);doc.text('To,',15,y+1);y+=6;doc.setFontSize(11.5);doc.text(clean(customer.fullName),15,y);y+=4.5;const customerAddress=[customer.address,customer.villageCity,customer.taluka,customer.district?`Dist: ${customer.district}`:'',customer.pinCode].filter(Boolean).join(', ');y=lines(doc,customerAddress,15,y,170,9.2,'normal',4);y=lines(doc,`Contact: +91 ${customer.mobile}`,15,y,170,9.2,'normal',4);sectionRule(doc,y+1);y+=10;doc.setFont('times','bold');doc.setFontSize(10.3);doc.text(clean(`SUBJECT: ${quote.dcCapacityKw.toFixed(2)} kW Rooftop Solar (${quote.scheme})`),15,y);sectionRule(doc,y+3);y+=13;doc.setFontSize(10);doc.text('DETAILS OF SUPPLY',15,y);y+=3;y=supplyTable(doc,input,y);doc.setFont('times','bold');doc.setFontSize(10);doc.text('Grand Total (Including GST):',15,y+7);doc.text(money(quote.grandTotal),95,y+7);y+=12;if(quote.loanRequired){doc.setFontSize(8.2);doc.text('Loan Commercials:',15,y+5);doc.setFont('times','normal');doc.text(clean(`Base EPC ${money(quote.loanBasePrice??quote.grandTotal)} | Gross-up ${quote.loanGrossUpPercent??10}%: ${money(quote.loanGrossUpAmount??0)} | File charge: ${money(quote.loanFileCharge??0)}`),43,y+5);y+=8;}sectionRule(doc,y);y+=11;doc.setFont('times','bold');doc.setFontSize(10);doc.text('SUBSIDY DETAILS (INFORMATIONAL ONLY)',15,y);y+=3;y=subsidyTable(doc,input,y);doc.setFont('times','italic');doc.setFontSize(7.6);doc.text('Subsidy is subject to authority approval and is not deducted from this quotation value.',15,y+5);doc.setFont('times','bold');doc.setFontSize(9.5);doc.text('Net Amount Payable:',15,y+12);doc.text(money(quote.grandTotal),57,y+12);doc.text('Amount in Words:',15,y+19);doc.setFont('times','normal');doc.text(clean(amountInWords(quote.grandTotal)),49,y+19);footer(doc,input);}

function drawBom(doc:jsPDF,input:QuotationPdfInput,top:number){const visible=input.quote.items.filter(item=>item.selected&&(input.copyType==='internal'||!item.internalOnly));const rows=visible.length?visible:[];const x=15;const widths=[10,48,42,62,28];const pos=[x];widths.forEach(w=>pos.push((pos.at(-1)??x)+w));const maxTableHeight=118;const rowH=Math.max(6.2,Math.min(8,maxTableHeight/Math.max(rows.length+1,1)));const height=rowH*(rows.length+1);doc.setLineWidth(.25);doc.rect(x,top,190,height);pos.slice(1,-1).forEach(px=>doc.line(px,top,px,top+height));for(let i=1;i<=rows.length;i++)doc.line(x,top+rowH*i,x+190,top+rowH*i);doc.setFont('times','bold');doc.setFontSize(7.7);['Sr.','Component','Brand / Model','Specification','Qty'].forEach((h,i)=>doc.text(h,pos[i]!+widths[i]!/2,top+rowH*.65,{align:'center'}));rows.forEach((item,index)=>{const y=top+rowH*(index+1)+rowH*.62;const component=item.description==='Monitoring System'?'Online Monitoring System':item.description;const specification=component==='Online Monitoring System'?'Mobile App + Remote Monitoring':item.specification||'-';doc.setFont('times','normal');doc.setFontSize(rows.length>12?6.6:7.4);doc.text(String(index+1),pos[0]!+widths[0]!/2,y,{align:'center'});doc.text(wrap(doc,component,widths[1]!-3).slice(0,2),pos[1]!+1.5,y);doc.text(wrap(doc,item.brand||'-',widths[2]!-3).slice(0,2),pos[2]!+1.5,y);doc.text(wrap(doc,specification,widths[3]!-3).slice(0,2),pos[3]!+1.5,y);doc.text(clean(`${item.quantity} ${item.unit}`),pos[4]!+widths[4]!-1.5,y,{align:'right'});});return top+height;}

function drawPageTwo(doc:jsPDF,input:QuotationPdfInput,logo:string|null){const{quote,settings}=input;const{bank,company}=settings;header(doc,input,logo);let y=33;doc.setFont('times','bold');doc.setFontSize(11);doc.text('BANK DETAILS',15,y);y+=7;doc.setFontSize(10.5);doc.text(clean(bank.accountHolder),15,y);y+=5;doc.setFontSize(9.5);const bankRows=[['Bank Name',bank.bankName],['A/c No.',bank.accountNumber],['IFSC Code',bank.ifsc],['Branch',bank.branch]];bankRows.forEach(([label,value])=>{doc.setFont('times','bold');doc.text(`${label} :`,15,y);doc.setFont('times','normal');doc.text(clean(value),42,y);y+=5;});sectionRule(doc,y);y+=11;doc.setFont('times','bold');doc.setFontSize(11);doc.text('PAYMENT TERMS',15,y);y+=7;const paymentTerms=quote.paymentTerms.split(/[;\n]+/).map(term=>term.trim()).filter(Boolean);paymentTerms.forEach(term=>{doc.setFont('times','normal');doc.setFontSize(9.6);doc.text('-',21,y);doc.text(clean(term),28,y);y+=6;});y+=5;sectionRule(doc,y);y+=11;doc.setFont('times','bold');doc.setFontSize(11);doc.text('SYSTEM BILL OF MATERIALS (BOM)',15,y);y+=7;doc.setFontSize(9.8);doc.text('Project Capacity:',15,y);doc.setFont('times','normal');doc.text(`${quote.dcCapacityKw.toFixed(3)} kW`,48,y);y+=3;y=drawBom(doc,input,y);if(input.copyType==='internal'){y+=6;doc.setDrawColor(80,80,80);doc.rect(15,y,190,15);doc.setFont('times','bold');doc.setFontSize(8.5);doc.text('INTERNAL COMMERCIALS - CONFIDENTIAL',18,y+5);doc.setFont('times','normal');doc.text(clean(`Suggested ${money(quote.suggestedPrice??quote.grandTotal)} | Dealer Commission ${money(quote.dealerCommission??0)} | Internal Cost ${money(quote.internalCost??0)}`),18,y+11);y+=15;}y=Math.min(y+9,245);doc.setFont('times','bold');doc.setFontSize(10);doc.text('Declaration:',15,y);y+=6;doc.setFont('times','normal');doc.setFontSize(9);doc.text('We hereby declare that the information given above is true and correct to the best of our knowledge.',15,y);y+=6;doc.setFont('times','bold');doc.text('Validity of Quotation:',15,y);doc.setFont('times','normal');doc.text(`${quote.validityDays} Days from the date of issue.`,53,y);doc.setFont('times','bold');doc.text('Authorised Signatory',15,263);doc.text(clean(company.legalName),15,269);doc.setFont('times','normal');doc.text('(Stamp & Signature)',15,274);footer(doc,input);}

export async function createQuotationPdf(input:QuotationPdfInput){const{jsPDF}=await import('jspdf');const doc=new jsPDF({unit:'mm',format:'a4',orientation:'portrait',compress:true});let logo:string|null=null;try{logo=await imageData('/brand/ratneswar-wordmark.png');}catch{logo=null;}drawPageOne(doc,input,logo);doc.addPage('a4','portrait');drawPageTwo(doc,input,logo);doc.setProperties({title:`Quotation ${input.quote.quoteNo}`,subject:`${input.quote.dcCapacityKw.toFixed(3)} kWp Rooftop Solar Quotation`,author:input.settings.company.tradeName,creator:'Ratneswar Solar CRM'});return doc;}
export async function downloadVectorQuotationPdf(input:QuotationPdfInput,filename:string){const pdf=await createQuotationPdf(input);pdf.save(filename);}
export async function openVectorQuotationPdf(input:QuotationPdfInput,filename:string){const popup=window.open('','_blank');if(popup)popup.document.write('<title>Preparing quotation...</title><p style="font:16px sans-serif;padding:24px">Preparing selectable A4 quotation PDF...</p>');const pdf=await createQuotationPdf(input);const blob=pdf.output('blob');const url=URL.createObjectURL(blob);if(popup)popup.location.href=url;else pdf.save(filename);window.setTimeout(()=>URL.revokeObjectURL(url),120000);}
