import { AlertTriangle, BadgeIndianRupee, Boxes, FileClock, FolderKanban, Gauge, Users } from 'lucide-react';
import { useCrm } from '../lib/CrmContext';
import { formatInr } from '../services/calculations';
import { projectStages } from '../services/workflow';
import { PageHeader, Status } from '../components/Ui';
import type { LucideIcon } from 'lucide-react';

export function Dashboard() {
  const { data }=useCrm(); if(!data)return null; const dealer=data.profile.role==='dealer'; const admin=data.profile.role==='admin'; const shortages=data.projects.flatMap((p)=>p.materials).filter((m)=>m.shortageQty>0).length; const installedStages=['installation_done','inspection_pending','inspection_done','meter_pending','meter_done','commissioning_done','subsidy_pending','subsidy_passed','handover_completed','project_closed']; const installed=data.projects.filter((p)=>installedStages.includes(p.stage)); const capacity=installed.reduce((s,p)=>s+p.acceptedQuoteSnapshot.dcCapacityKw,0); const commissions=data.commissions.reduce((s,c)=>({total:s.total+c.totalCommission,paid:s.paid+c.amountPaid}),{total:0,paid:0});
  const cards: Array<readonly [string,string|number,LucideIcon,string]>=dealer?[
    ['My Customers',data.customers.length,Users,'info'],['My Quotations',data.quotations.length,FileClock,'neutral'],['Draft',data.quotations.filter((q)=>q.status==='draft').length,FileClock,'warn'],['Sent / Pending',data.quotations.filter((q)=>['sent','pending'].includes(q.status)).length,FileClock,'info'],['Rejected',data.quotations.filter((q)=>q.status==='rejected').length,AlertTriangle,'bad'],
  ]:[
    ['Customers',data.customers.length,Users,'info'],['Active Projects',data.projects.filter((p)=>p.stage!=='project_closed').length,FolderKanban,'good'],['Pending Quotations',data.quotations.filter((q)=>['sent','pending'].includes(q.status)).length,FileClock,'warn'],['Installed Capacity',`${capacity.toFixed(2)} kW`,Gauge,'good'],['Inspection Pending',data.projects.filter((p)=>p.stage==='inspection_pending').length,FileClock,'warn'],['Subsidy Pending',data.projects.filter((p)=>p.stage==='subsidy_pending').length,BadgeIndianRupee,'warn'],['Material Shortages',shortages,Boxes,shortages?'bad':'good'],...(admin?[['Commission Outstanding',formatInr(commissions.total-commissions.paid),BadgeIndianRupee,'warn'] as const]:[])];
  return <><PageHeader title={dealer?'Dealer Dashboard':admin?'Admin Command Centre':'District Operations Dashboard'} subtitle={dealer?'Manage your customers and customer-facing quotations.':'Live role-scoped Solar EPC workflow, capacity, documents and alerts.'}/><div className="stats-grid">{cards.map(([label,value,Icon,tone])=><article className={`stat stat--${tone}`} key={label}><div><span>{label}</span><strong>{value}</strong></div><Icon size={22}/></article>)}</div>
    {!dealer&&<div className="two-col"><section className="card"><div className="card__title"><h2>Projects by Stage</h2></div><div className="stage-summary">{projectStages.map((stage)=>{const count=data.projects.filter((p)=>p.stage===stage.id).length;return count>0&&<div key={stage.id}><span>{stage.label}</span><strong>{count}</strong></div>;})}{!data.projects.length&&<p className="muted">Projects appear when a sent or pending quotation is approved.</p>}</div></section><section className="card"><div className="card__title"><h2>Attention Required</h2></div><div className="attention-list">{shortages>0&&<div><AlertTriangle size={18}/><span>{shortages} material requirement lines have shortages.</span><Status tone="bad">Action</Status></div>}{data.quotations.filter((q)=>q.status==='sent').map((q)=><div key={q.id}><FileClock size={18}/><span>{q.quoteNo} requires customer follow-up.</span><Status tone="warn">Sent</Status></div>)}{!shortages&&!data.quotations.some((q)=>q.status==='sent')&&<div className="success-line">No critical pending alert.</div>}</div></section></div>}
  </>;
}
