import { useState } from 'react';
import { FileScan, PackagePlus, Pencil, Trash2, Upload } from 'lucide-react';
import { Empty, Field, PageHeader, Status } from '../components/Ui';
import { Modal } from '../components/Modal';
import { useCrm } from '../lib/CrmContext';
import { confirmVendorInvoice, createInventoryItem, invokeAiImporter, uploadPrivateFile } from '../services/repository';
import { formatDate, formatInr } from '../services/calculations';
import type { InventoryItem, StockTransaction } from '../types/domain';

type InvoiceRow = { inventoryItemId?: string; description: string; brand?: string; model?: string; hsn?: string; quantity: number; unit: string; rate: number; tax: number; total: number; confidence?: number; source?: string };
type InvoiceReview = { vendorName: string; gstin?: string; invoiceNumber: string; invoiceDate: string; fileHash: string; total: number; rows: InvoiceRow[] };

export function Inventory() {
  const { data, archiveInventoryItem, saving } = useCrm(); const [manual, setManual] = useState(false); const [importing, setImporting] = useState(false); const [itemMaster,setItemMaster]=useState<InventoryItem|'new'|null>(null);
  if (!data || data.profile.role === 'dealer') return <Empty title="Access denied" detail="Inventory is not available to Dealer users." />;
  return <>
    <PageHeader title="Inventory" subtitle="Item masters are editable; quantities remain protected by the append-only stock ledger." actions={data.profile.role === 'admin' ? <><button className="btn" onClick={() => setItemMaster('new')}><PackagePlus size={16}/> New Item Master</button><button className="btn" onClick={() => setImporting(true)}><FileScan size={16} /> Import Vendor Invoice</button><button className="btn btn--primary" onClick={() => setManual(true)}><PackagePlus size={16} /> Manual Stock Entry</button></> : undefined} />
    <section className="card table-card"><table><thead><tr><th>Item</th><th>Warehouse</th><th>On Hand</th><th>Reserved</th><th>Available</th><th>Average Rate</th><th>Health</th>{data.profile.role === 'admin'&&<th>Actions</th>}</tr></thead><tbody>{data.inventory.map((item) => <tr key={item.id}><td><strong>{item.itemName}</strong><small>{item.itemCode} · {[item.brand,item.model,item.specification].filter(Boolean).join(' · ')}</small></td><td>{item.warehouseDistrict || '-'}</td><td>{item.onHand} {item.unit}</td><td>{item.reserved}</td><td>{item.available}</td><td>{formatInr(item.averageRate)}</td><td>{item.available <= item.reorderLevel ? <Status tone="bad">Low Stock</Status> : <Status tone="good">Available</Status>}</td>{data.profile.role === 'admin'&&<td><div className="row-actions"><button className="icon-btn" title="Edit item master" onClick={()=>setItemMaster(item)}><Pencil size={15}/></button><button className="icon-btn bad" disabled={saving} title="Archive item" onClick={async()=>{const reason=window.prompt(`Reason for archiving ${item.itemName}?`)??'';if(!reason.trim())return;if(!window.confirm('Archive this item master? Existing stock history will remain.'))return;await archiveInventoryItem(item.id,reason);}}><Trash2 size={15}/></button></div></td>}</tr>)}</tbody></table>{!data.inventory.length && <Empty title="No inventory items" detail="Create item masters during manual stock entry or map vendor invoice rows." />}</section>
    <section className="card table-card"><div className="card__title"><h2>Recent Stock Transactions</h2></div><table><thead><tr><th>Date</th><th>Item</th><th>Type</th><th>Quantity</th><th>Reference</th><th>Reason</th></tr></thead><tbody>{data.stockTransactions.slice(0, 100).map((tx) => <tr key={tx.id}><td>{formatDate(tx.occurredAt)}</td><td>{data.inventory.find((x) => x.id === tx.inventoryItemId)?.itemName ?? tx.inventoryItemId}</td><td><Status tone="info">{tx.transactionType}</Status></td><td>{tx.quantity}</td><td>{tx.referenceNo || '-'}</td><td>{tx.reason || '-'}</td></tr>)}</tbody></table></section>
    {manual && <ManualStock onClose={() => setManual(false)} />}{importing && <VendorInvoiceImporter onClose={() => setImporting(false)} />}{itemMaster&&<ItemMasterForm initial={itemMaster==='new'?undefined:itemMaster} onClose={()=>setItemMaster(null)}/>} 
  </>;
}

function ItemMasterForm({initial,onClose}:{initial?:InventoryItem;onClose:()=>void}){const{data,refresh,updateInventoryItem}=useCrm();const districtId=data?.districts.find((d)=>d.name===initial?.warehouseDistrict)?.id??'';const[v,setV]=useState({id:initial?.id,itemCode:initial?.itemCode??'',itemName:initial?.itemName??'',category:initial?.category??'PV Module',brand:initial?.brand??'',model:initial?.model??'',specification:initial?.specification??'',unit:initial?.unit??'Nos',districtId,serialized:false,reorderLevel:initial?.reorderLevel??0});const[busy,setBusy]=useState(false);const[error,setError]=useState('');return <Modal title={initial?'Edit Inventory Item Master':'New Inventory Item Master'} onClose={onClose}><form onSubmit={async(e)=>{e.preventDefault();setBusy(true);setError('');try{if(initial)await updateInventoryItem(v);else{await createInventoryItem(v);await refresh();}onClose();}catch(err){setError(err instanceof Error?err.message:'Item save failed.');}finally{setBusy(false);}}}><div className="form-grid"><Field label="Item Code"><input required value={v.itemCode} onChange={(e)=>setV({...v,itemCode:e.target.value.toUpperCase()})}/></Field><Field label="Item Name"><input required value={v.itemName} onChange={(e)=>setV({...v,itemName:e.target.value})}/></Field><Field label="Category"><input required value={v.category} onChange={(e)=>setV({...v,category:e.target.value})}/></Field><Field label="Brand"><input value={v.brand} onChange={(e)=>setV({...v,brand:e.target.value})}/></Field><Field label="Model"><input value={v.model} onChange={(e)=>setV({...v,model:e.target.value})}/></Field><Field label="Specification"><input value={v.specification} onChange={(e)=>setV({...v,specification:e.target.value})}/></Field><Field label="Unit"><input required value={v.unit} onChange={(e)=>setV({...v,unit:e.target.value})}/></Field><Field label="Warehouse District"><select value={v.districtId} onChange={(e)=>setV({...v,districtId:e.target.value})}><option value="">Central / All Districts</option>{data?.districts.map((d)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></Field><Field label="Reorder Level"><input type="number" min="0" value={v.reorderLevel} onChange={(e)=>setV({...v,reorderLevel:Number(e.target.value)})}/></Field><Field label="Serialised Item"><input type="checkbox" checked={v.serialized} disabled={Boolean(initial)} title={initial?'Serialisation cannot be changed after creation.':''} onChange={(e)=>setV({...v,serialized:e.target.checked})}/></Field></div>{initial&&<div className="alert alert--info">Editing changes the item master only. Stock quantities remain controlled through ledger transactions.</div>}{error&&<div className="alert alert--error">{error}</div>}<div className="form-actions"><button type="button" className="btn" onClick={onClose}>Cancel</button><button className="btn btn--primary" disabled={busy}>{busy?'Saving...':initial?'Save Changes':'Create Item'}</button></div></form></Modal>}

function ManualStock({ onClose }: { onClose: () => void }) {
  const { data, postStockTransaction, saving } = useCrm(); const [v, setV] = useState<StockTransaction>({ id: crypto.randomUUID(), inventoryItemId: data?.inventory[0]?.id ?? '', transactionType: 'opening', quantity: 0, idempotencyKey: crypto.randomUUID(), occurredAt: new Date().toISOString() });
  return <Modal title="Manual Stock Transaction" onClose={onClose}><form onSubmit={async (e) => { e.preventDefault(); await postStockTransaction(v); onClose(); }}><div className="form-grid"><Field label="Inventory Item"><select required value={v.inventoryItemId} onChange={(e) => setV({ ...v, inventoryItemId: e.target.value })}><option value="">Select item</option>{data?.inventory.map((x) => <option value={x.id} key={x.id}>{x.itemName} ({x.itemCode})</option>)}</select></Field><Field label="Transaction Type"><select value={v.transactionType} onChange={(e) => setV({ ...v, transactionType: e.target.value as StockTransaction['transactionType'] })}>{['opening','purchase','return','damage','adjustment'].map((x) => <option key={x} value={x}>{x}</option>)}</select></Field><Field label="Quantity"><input required type="number" step="0.001" min="0.001" value={v.quantity} onChange={(e) => setV({ ...v, quantity: Number(e.target.value) })} /></Field><Field label="Unit Rate"><input type="number" min="0" value={v.unitRate ?? ''} onChange={(e) => setV({ ...v, unitRate: Number(e.target.value) || undefined })} /></Field><Field label="Reference Number"><input value={v.referenceNo ?? ''} onChange={(e) => setV({ ...v, referenceNo: e.target.value })} /></Field><Field label="Reason (required for adjustments)"><textarea required={v.transactionType === 'adjustment' || v.transactionType === 'damage'} value={v.reason ?? ''} onChange={(e) => setV({ ...v, reason: e.target.value })} /></Field></div><div className="form-actions"><button type="button" className="btn" onClick={onClose}>Cancel</button><button className="btn btn--primary" disabled={saving || !v.inventoryItemId}>{saving ? 'Posting...' : 'Post Transaction'}</button></div></form></Modal>;
}

function VendorInvoiceImporter({ onClose }: { onClose: () => void }) {
  const { data, refresh } = useCrm(); const [file, setFile] = useState<File | null>(null); const [review, setReview] = useState<InvoiceReview | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const analyse = async () => { if (!file) return; setBusy(true); setError(''); try { const result = await invokeAiImporter('vendor_invoice', [file]); setReview(result.extraction as InvoiceReview); } catch (e) { setError(e instanceof Error ? e.message : 'Invoice analysis failed.'); } finally { setBusy(false); } };
  return <Modal title="Vendor Invoice Import" onClose={onClose} wide><div className="importer-drop"><Upload size={24} /><input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={(e) => setFile(e.target.files?.[0] ?? null)} /><button className="btn btn--primary" disabled={!file || busy} onClick={() => void analyse()}>{busy ? 'Analysing...' : 'Analyse Invoice'}</button></div>{error && <div className="alert alert--error">{error}</div>}
    {review && <><div className="form-grid"><Field label="Vendor"><input value={review.vendorName} onChange={(e) => setReview({ ...review, vendorName: e.target.value })} /></Field><Field label="GSTIN"><input value={review.gstin ?? ''} onChange={(e) => setReview({ ...review, gstin: e.target.value })} /></Field><Field label="Invoice Number"><input value={review.invoiceNumber} onChange={(e) => setReview({ ...review, invoiceNumber: e.target.value })} /></Field><Field label="Invoice Date"><input type="date" value={review.invoiceDate} onChange={(e) => setReview({ ...review, invoiceDate: e.target.value })} /></Field></div><div className="table-card"><table><thead><tr><th>Source Description</th><th>Inventory Mapping</th><th>Qty</th><th>Rate</th><th>Tax</th><th>Total</th><th>Evidence</th></tr></thead><tbody>{review.rows.map((row, index) => <tr key={index}><td><input value={row.description} onChange={(e) => setReview({ ...review, rows: review.rows.map((x,i) => i === index ? { ...x, description: e.target.value } : x) })} /></td><td><select value={row.inventoryItemId ?? ''} onChange={(e) => setReview({ ...review, rows: review.rows.map((x,i) => i === index ? { ...x, inventoryItemId: e.target.value } : x) })}><option value="">Map item</option>{data?.inventory.map((x) => <option value={x.id} key={x.id}>{x.itemName}</option>)}</select></td><td><input type="number" value={row.quantity} onChange={(e) => setReview({ ...review, rows: review.rows.map((x,i) => i === index ? { ...x, quantity: Number(e.target.value) } : x) })} /></td><td>{formatInr(row.rate)}</td><td>{row.tax}%</td><td>{formatInr(row.total)}</td><td><small>{Math.round((row.confidence ?? 0) * 100)}% · {row.source}</small></td></tr>)}</tbody></table></div><div className="form-actions"><strong>Total {formatInr(review.total)}</strong><button className="btn btn--primary" disabled={busy || review.rows.some((x) => !x.inventoryItemId)} onClick={async () => { setBusy(true); setError(''); try { if(!file) throw new Error('Original invoice file is missing.'); const path=`${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`; await uploadPrivateFile('inventory-invoices',path,file); await confirmVendorInvoice({ ...review, originalFileName: file.name, storagePath:path }); await refresh(); onClose(); } catch (e) { setError(e instanceof Error ? e.message : 'Stock posting failed.'); } finally { setBusy(false); } }}>Confirm Stock In</button></div></>}
  </Modal>;
}
