import { useState } from 'react';
import { BadgeIndianRupee, Boxes, Plus, ReceiptIndianRupee, UsersRound } from 'lucide-react';
import { Modal } from '../components/Modal';
import { Empty, Field, PageHeader, Status } from '../components/Ui';
import { useCrm } from '../lib/CrmContext';
import { formatInr } from '../services/calculations';
import type { CommissionPayment, Dealer, DealerCommission, Expense, Payment } from '../types/domain';

type FormType = 'dealer' | 'payment' | 'expense' | null;

export function Operations() {
  const { data, addDealer, addPayment, addExpense, saving } = useCrm();
  const [form, setForm] = useState<FormType>(null);
  const [commission, setCommission] = useState<DealerCommission | null>(null);
  if (!data) return null;
  const received = data.payments.reduce((s, p) => s + p.amount, 0);
  const spent = data.expenses.reduce((s, e) => s + e.amount, 0);
  return <>
    <PageHeader title="Operations and Finance" subtitle="Dealer master, commission ledger, customer receipts and project expenses." actions={<>{data.profile.role === 'admin' && <button className="btn" onClick={() => setForm('dealer')}><UsersRound size={16} /> Add Dealer</button>}<button className="btn" onClick={() => setForm('expense')}><ReceiptIndianRupee size={16} /> Expense</button><button className="btn btn--primary" onClick={() => setForm('payment')}><BadgeIndianRupee size={16} /> Customer Payment</button></>} />
    <div className="stats-grid compact"><article className="stat stat--good"><div><span>Payments Received</span><strong>{formatInr(received)}</strong></div><BadgeIndianRupee size={20} /></article><article className="stat stat--warn"><div><span>Expenses</span><strong>{formatInr(spent)}</strong></div><ReceiptIndianRupee size={20} /></article><article className="stat stat--info"><div><span>Inventory Value</span><strong>{formatInr(data.inventory.reduce((s, i) => s + i.onHand * i.averageRate, 0))}</strong></div><Boxes size={20} /></article></div>
    <div className="two-col"><section className="card table-card"><div className="card__title"><h2>Inventory Balance</h2></div>{data.inventory.length ? <table><thead><tr><th>Item</th><th>Stock</th><th>Available</th><th>Reorder</th></tr></thead><tbody>{data.inventory.map((i) => <tr key={i.id}><td><strong>{i.itemName}</strong><small>{i.itemCode} | {i.brand}</small></td><td>{i.onHand} {i.unit}</td><td>{i.available}</td><td>{i.available <= i.reorderLevel ? <Status tone="bad">Reorder</Status> : <Status tone="good">OK</Status>}</td></tr>)}</tbody></table> : <Empty title="No inventory" detail="Stock inward transactions will create balances here." />}</section>
      <section className="card table-card"><div className="card__title"><h2>Dealers</h2></div>{data.dealers.length ? <table><thead><tr><th>Name</th><th>District</th><th>Commission</th></tr></thead><tbody>{data.dealers.map((d) => <tr key={d.id}><td><strong>{d.name}</strong><small>{d.mobile}</small></td><td>{d.district}</td><td>{d.commissionType === 'percentage' ? `${d.commissionValue}%` : formatInr(d.commissionValue)}</td></tr>)}</tbody></table> : <Empty title="No dealer" detail="Add dealers with fixed or percentage commission rules." />}</section></div>
    <div className="two-col"><section className="card table-card"><div className="card__title"><h2>Recent Payments</h2></div>{data.payments.length ? <table><thead><tr><th>Date</th><th>Customer</th><th>Mode</th><th>Amount</th></tr></thead><tbody>{data.payments.slice(0, 10).map((p) => <tr key={p.id}><td>{p.paymentDate}</td><td>{data.customers.find((c) => c.id === p.customerId)?.fullName}</td><td>{p.mode}</td><td>{formatInr(p.amount)}</td></tr>)}</tbody></table> : <Empty title="No payment" detail="Record advance and milestone collections." />}</section>
      <section className="card table-card"><div className="card__title"><h2>Recent Expenses</h2></div>{data.expenses.length ? <table><thead><tr><th>Date</th><th>Category</th><th>Project</th><th>Amount</th></tr></thead><tbody>{data.expenses.slice(0, 10).map((e) => <tr key={e.id}><td>{e.expenseDate}</td><td>{e.category}<small>{e.vendor}</small></td><td>{data.projects.find((p) => p.id === e.projectId)?.projectNo ?? '-'}</td><td>{formatInr(e.amount)}</td></tr>)}</tbody></table> : <Empty title="No expense" detail="Record project and office expenses." />}</section></div>
    <section className="card table-card"><div className="card__title"><h2>Dealer Commission Ledger</h2></div>{data.commissions.length ? <table><thead><tr><th>Dealer</th><th>Customer / Project</th><th>Total</th><th>Paid</th><th>Outstanding</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.commissions.map((c) => <tr key={c.id}><td>{data.dealers.find((d) => d.id === c.dealerId)?.name}</td><td>{data.customers.find((x) => x.id === c.customerId)?.fullName}<small>{data.projects.find((x) => x.id === c.projectId)?.projectNo}</small></td><td>{formatInr(c.totalCommission)}</td><td>{formatInr(c.amountPaid)}</td><td>{formatInr(c.totalCommission - c.amountPaid)}</td><td><Status tone={c.status === 'paid' ? 'good' : c.status === 'partial' ? 'warn' : 'neutral'}>{c.status}</Status></td><td>{data.profile.role === 'admin' && c.status !== 'paid' ? <button className="btn btn--small" onClick={() => setCommission(c)}>Record Payment</button> : '-'}</td></tr>)}</tbody></table> : <Empty title="No commission entries" detail="A ledger entry is created automatically when an approved quotation creates a dealer-linked project." />}</section>
    {form === 'dealer' && <DealerForm saving={saving} onClose={() => setForm(null)} onSave={async (d) => { await addDealer(d); setForm(null); }} />}
    {form === 'payment' && <PaymentForm saving={saving} onClose={() => setForm(null)} onSave={async (p) => { await addPayment(p); setForm(null); }} />}
    {form === 'expense' && <ExpenseForm saving={saving} onClose={() => setForm(null)} onSave={async (e) => { await addExpense(e); setForm(null); }} />}
    {commission && <CommissionPaymentForm commission={commission} onClose={() => setCommission(null)} />}
  </>;
}

function DealerForm({ onClose, onSave, saving }: { onClose: () => void; onSave: (v: Dealer) => Promise<void>; saving: boolean }) {
  const [v, setV] = useState<Dealer>({ id: crypto.randomUUID(), dealerNo: '', name: '', mobile: '', district: 'Kutch', commissionType: 'percentage', commissionValue: 2, active: true });
  return <Modal title="Add Dealer" onClose={onClose}><form onSubmit={async (e) => { e.preventDefault(); await onSave(v); }}><div className="form-grid"><Field label="Name"><input required value={v.name} onChange={(e) => setV({ ...v, name: e.target.value })} /></Field><Field label="Mobile"><input required value={v.mobile} onChange={(e) => setV({ ...v, mobile: e.target.value })} /></Field><Field label="District"><input required value={v.district} onChange={(e) => setV({ ...v, district: e.target.value })} /></Field><Field label="Commission"><div className="compound"><select value={v.commissionType} onChange={(e) => setV({ ...v, commissionType: e.target.value as Dealer['commissionType'] })}><option value="percentage">%</option><option value="fixed">₹</option></select><input type="number" value={v.commissionValue} onChange={(e) => setV({ ...v, commissionValue: Number(e.target.value) })} /></div></Field></div><FormButtons onClose={onClose} saving={saving} /></form></Modal>;
}

function PaymentForm({ onClose, onSave, saving }: { onClose: () => void; onSave: (v: Payment) => Promise<void>; saving: boolean }) {
  const { data } = useCrm(); const first = data?.customers[0]?.id ?? '';
  const [v, setV] = useState<Payment>({ id: crypto.randomUUID(), customerId: first, paymentType: 'Advance', amount: 0, paymentDate: new Date().toISOString().slice(0, 10), mode: 'Bank Transfer' });
  return <Modal title="Record Payment" onClose={onClose}><form onSubmit={async (e) => { e.preventDefault(); await onSave(v); }}><div className="form-grid"><Field label="Customer"><select value={v.customerId} onChange={(e) => setV({ ...v, customerId: e.target.value })}>{data?.customers.map((c) => <option value={c.id} key={c.id}>{c.fullName}</option>)}</select></Field><Field label="Project"><select value={v.projectId ?? ''} onChange={(e) => setV({ ...v, projectId: e.target.value || null })}><option value="">None</option>{data?.projects.filter((p) => p.customerId === v.customerId).map((p) => <option value={p.id} key={p.id}>{p.projectNo}</option>)}</select></Field><Field label="Amount"><input required min="1" type="number" value={v.amount} onChange={(e) => setV({ ...v, amount: Number(e.target.value) })} /></Field><Field label="Date"><input type="date" value={v.paymentDate} onChange={(e) => setV({ ...v, paymentDate: e.target.value })} /></Field><Field label="Mode"><select value={v.mode} onChange={(e) => setV({ ...v, mode: e.target.value })}>{['Bank Transfer', 'UPI', 'Cheque', 'Cash', 'Finance Disbursement'].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Reference"><input value={v.referenceNo ?? ''} onChange={(e) => setV({ ...v, referenceNo: e.target.value })} /></Field></div><FormButtons onClose={onClose} saving={saving} /></form></Modal>;
}

function ExpenseForm({ onClose, onSave, saving }: { onClose: () => void; onSave: (v: Expense) => Promise<void>; saving: boolean }) {
  const { data } = useCrm(); const [v, setV] = useState<Expense>({ id: crypto.randomUUID(), expenseDate: new Date().toISOString().slice(0, 10), category: 'Material', amount: 0 });
  return <Modal title="Record Expense" onClose={onClose}><form onSubmit={async (e) => { e.preventDefault(); await onSave(v); }}><div className="form-grid"><Field label="Project"><select value={v.projectId ?? ''} onChange={(e) => setV({ ...v, projectId: e.target.value || null })}><option value="">Office / General</option>{data?.projects.map((p) => <option value={p.id} key={p.id}>{p.projectNo}</option>)}</select></Field><Field label="Date"><input type="date" value={v.expenseDate} onChange={(e) => setV({ ...v, expenseDate: e.target.value })} /></Field><Field label="Category"><select value={v.category} onChange={(e) => setV({ ...v, category: e.target.value })}>{['Material', 'Transport', 'Installation', 'Labour', 'Documentation', 'Office', 'Other'].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Amount"><input required min="1" type="number" value={v.amount} onChange={(e) => setV({ ...v, amount: Number(e.target.value) })} /></Field><Field label="Vendor"><input value={v.vendor ?? ''} onChange={(e) => setV({ ...v, vendor: e.target.value })} /></Field><Field label="Notes"><input value={v.notes ?? ''} onChange={(e) => setV({ ...v, notes: e.target.value })} /></Field></div><FormButtons onClose={onClose} saving={saving} /></form></Modal>;
}

function FormButtons({ onClose, saving }: { onClose: () => void; saving: boolean }) { return <div className="form-actions"><button type="button" className="btn" onClick={onClose}>Cancel</button><button className="btn btn--primary" disabled={saving}><Plus size={15} /> Save</button></div>; }

function CommissionPaymentForm({ commission, onClose }: { commission: DealerCommission; onClose: () => void }) {
  const { payCommission, saving } = useCrm(); const outstanding = commission.totalCommission - commission.amountPaid;
  const [v, setV] = useState<CommissionPayment>({ id: crypto.randomUUID(), commissionId: commission.id, paymentDate: new Date().toISOString().slice(0,10), amount: outstanding, mode: 'Bank Transfer' });
  return <Modal title="Record Dealer Commission Payment" onClose={onClose}><form onSubmit={async (e) => { e.preventDefault(); await payCommission(v); onClose(); }}><div className="form-grid"><Field label="Outstanding"><input readOnly value={formatInr(outstanding)} /></Field><Field label="Payment Date"><input required type="date" value={v.paymentDate} onChange={(e) => setV({ ...v, paymentDate: e.target.value })} /></Field><Field label="Amount"><input required type="number" min="1" max={outstanding} value={v.amount} onChange={(e) => setV({ ...v, amount: Number(e.target.value) })} /></Field><Field label="Mode"><select value={v.mode} onChange={(e) => setV({ ...v, mode: e.target.value })}>{['Bank Transfer','UPI','Cheque','Cash'].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Reference Number"><input value={v.referenceNo ?? ''} onChange={(e) => setV({ ...v, referenceNo: e.target.value })} /></Field><Field label="Notes"><textarea value={v.notes ?? ''} onChange={(e) => setV({ ...v, notes: e.target.value })} /></Field></div><FormButtons onClose={onClose} saving={saving} /></form></Modal>;
}
