import { useState } from 'react';
import { Boxes, Clock3, Eye, FileText, History, MapPin, Pencil, Plus, Trash2, XCircle } from 'lucide-react';
import { Modal } from '../components/Modal';
import { Empty, Field, PageHeader, Status } from '../components/Ui';
import { useCrm } from '../lib/CrmContext';
import { calculateSplitGst, formatDate, formatInr } from '../services/calculations';
import { allowedNextStages, projectStages } from '../services/workflow';
import type { InstallationDetails, Invoice, MaterialRequirement, Project, ProjectStage } from '../types/domain';
import { InvoicePrint } from './InvoicePrint';

export const invoiceEligibleStages: ProjectStage[] = ['installation_done','inspection_pending','inspection_done','meter_pending','meter_done','commissioning_done','subsidy_pending','subsidy_passed','handover_completed','project_closed'];
export const canIssueInvoice = (stage: ProjectStage) => invoiceEligibleStages.includes(stage);

export function Projects() {
  const { data } = useCrm(); const [selected, setSelected] = useState<Project | null>(null); if (!data || data.profile.role === 'dealer') return <Empty title="Access denied" detail="Dealers cannot access projects." />;
  return <><PageHeader title="Projects" subtitle="Approved quotation projects with validated stage transitions, immutable history and inventory requirements." />
    <div className="project-grid">{data.projects.map((project) => { const customer=data.customers.find((c)=>c.id===project.customerId); const shortages=project.materials.reduce((s,m)=>s+m.shortageQty,0); return <article className="project-card" key={project.id}><header><div><strong>{project.projectNo}</strong><span>{customer?.fullName??'Archived customer'}</span></div><Status tone={project.stage==='project_closed'?'good':'info'}>{projectStages.find((s)=>s.id===project.stage)?.label}</Status></header><div className="project-card__body"><p><MapPin size={15}/>{customer?.villageCity??'Customer archived'}, {project.district}</p><p><Boxes size={15}/>{shortages?`${shortages} item lines short`:'Materials covered'}</p><p><Clock3 size={15}/>{formatDate(project.updatedAt)}</p></div><footer><strong>{formatInr(project.acceptedQuoteSnapshot.grandTotal)}</strong><button className="btn btn--small" onClick={()=>setSelected(project)}><Eye size={14}/> Open</button></footer></article>;})}{!data.projects.length&&<div className="card"><Empty title="No project yet" detail="Approve a sent or pending quotation to create its project."/></div>}</div>{selected&&<ProjectDetail project={data.projects.find((p)=>p.id===selected.id)??selected} onClose={()=>setSelected(null)}/>}</>;
}

function ProjectDetail({ project, onClose }: { project: Project; onClose: () => void }) {
  const { data, changeProjectStage, deleteProject, cancelCustomerInvoice, saving }=useCrm(); const next=allowedNextStages(project.stage); const [stage,setStage]=useState<ProjectStage>(next[0]??project.stage); const [note,setNote]=useState(''); const [override,setOverride]=useState(''); const [invoicePreview,setInvoicePreview]=useState<Invoice|null>(null); const [install,setInstall]=useState(false); const [editMaterials,setEditMaterials]=useState(false);
  if(!data)return null; const customer=data.customers.find((c)=>c.id===project.customerId); const invoice=data.invoices.find((i)=>i.projectId===project.id&&i.status!=='cancelled'); const cancelledInvoice=data.invoices.find((i)=>i.projectId===project.id&&i.status==='cancelled'); const admin=data.profile.role==='admin';
  return <Modal title={project.projectNo} onClose={onClose} wide><div className="project-detail-head"><div><strong>{customer?.fullName??'Archived customer'}</strong><span>{customer?`${customer.mobile} · ${customer.villageCity}, ${customer.district}`:'The customer record is archived; Admin cleanup remains available.'}</span></div><div><strong>{project.acceptedQuoteSnapshot.dcCapacityKw.toFixed(3)} kW</strong><span>{project.acceptedQuoteSnapshot.panelBrand} {project.acceptedQuoteSnapshot.panelTechnology}</span></div><div><strong>{formatInr(project.acceptedQuoteSnapshot.grandTotal)}</strong><span>Accepted quotation snapshot</span></div></div>
    <section className="form-section"><h3>Update Project Stage</h3><div className="inline-form"><Field label="Allowed Next Stage"><select value={stage} onChange={(e)=>setStage(e.target.value as ProjectStage)}>{next.map((id)=><option value={id} key={id}>{projectStages.find((s)=>s.id===id)?.label}</option>)}{admin&&projectStages.filter((x)=>!next.includes(x.id)&&x.id!==project.stage).map((x)=><option value={x.id} key={x.id}>Admin override: {x.label}</option>)}</select></Field><Field label="Stage Note"><input required value={note} onChange={(e)=>setNote(e.target.value)} placeholder="Progress, evidence or blocker"/></Field>{admin&&!next.includes(stage)&&stage!==project.stage&&<Field label="Admin Override Reason"><input required value={override} onChange={(e)=>setOverride(e.target.value)}/></Field>}<button className="btn btn--primary" disabled={saving||stage===project.stage||!note.trim()||(!next.includes(stage)&&!override.trim())} onClick={async()=>{await changeProjectStage(project.id,stage,note,override);setNote('');setOverride('');}}>Update Stage</button></div>{!next.length&&<p className="muted">This project is closed. Admin may reopen it only with an audited override reason.</p>}</section>
    <div className="two-col"><section className="card card--inner"><div className="card__title"><h3><Boxes size={17}/> Material Requirement</h3><button className="btn btn--small" onClick={()=>setEditMaterials(true)}><Pencil size={14}/> Edit Materials</button></div><div className="material-list">{project.materials.map((m)=><div key={m.id}><div><strong>{m.itemName}</strong><span>{m.specification}</span></div><div className="qty-pills"><span>Required {m.requiredQty}</span><span>Reserved {m.reservedQty}</span><span>Issued {m.issuedQty}</span>{m.shortageQty>0&&<Status tone="bad">Short {m.shortageQty}</Status>}</div></div>)}</div></section><section className="card card--inner"><div className="card__title"><h3><History size={17}/> Complete Stage History</h3></div><div className="timeline">{[...project.stageHistory].reverse().map((h)=><div key={h.id}><i/><div><strong>{projectStages.find((s)=>s.id===h.toStage)?.label}</strong><span>{new Date(h.changedAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} · {h.changedBy}</span>{h.note&&<p>{h.note}</p>}</div></div>)}</div></section></div>
    {cancelledInvoice&&<div className="alert alert--info">Invoice {cancelledInvoice.invoiceNo} is cancelled. Admin can now delete this erroneous project.</div>}
    <div className="form-actions">{admin&&<button className="btn btn--danger" disabled={saving} onClick={async()=>{const reason=window.prompt('Reason for deleting this erroneous project (required)')??'';if(!reason.trim()||!window.confirm(`Delete ${project.projectNo}? An active invoice must be cancelled first. Issued stock and recorded payments still block deletion.`))return;await deleteProject(project.id,reason);onClose();}}><Trash2 size={16}/> Delete Project</button>}<button className="btn" onClick={onClose}>Close</button>{invoice&&admin&&<button className="btn btn--danger" disabled={saving} onClick={async()=>{const reason=window.prompt(`Cancellation reason for ${invoice.invoiceNo} (required)`)??'';if(!reason.trim()||!window.confirm(`Cancel invoice ${invoice.invoiceNo}? This action is audited.`))return;await cancelCustomerInvoice(invoice.id,reason);setInvoicePreview(null);}}><XCircle size={16}/> Cancel Invoice</button>}{invoice&&customer?<button className="btn btn--primary" onClick={()=>setInvoicePreview(invoice)}><FileText size={16}/> View Invoice</button>:!cancelledInvoice?<button className="btn btn--primary" disabled={!canIssueInvoice(project.stage)} onClick={()=>setInstall(true)} title={!canIssueInvoice(project.stage)?'Available after Project Installation Done':''}><FileText size={16}/> Installation Details and Invoice</button>:null}</div>
    {editMaterials&&<ProjectMaterialsForm project={project} onClose={()=>setEditMaterials(false)}/>} {install&&<InstallationForm project={project} onClose={()=>setInstall(false)}/>} {invoicePreview&&customer&&<InvoicePrint invoice={invoicePreview} project={project} customer={customer} onClose={()=>setInvoicePreview(null)}/>}</Modal>;
}

function ProjectMaterialsForm({project,onClose}:{project:Project;onClose:()=>void}){
  const{saveProjectMaterials,saving}=useCrm();const[materials,setMaterials]=useState<MaterialRequirement[]>(project.materials.map((item)=>({...item})));const[reason,setReason]=useState('');
  const patch=(index:number,value:Partial<MaterialRequirement>)=>setMaterials((rows)=>rows.map((row,i)=>i===index?{...row,...value}:row));
  return <Modal title="Edit Project Material Requirements" onClose={onClose} wide><form onSubmit={async(e)=>{e.preventDefault();await saveProjectMaterials(project.id,materials,reason);onClose();}}><div className="alert alert--info">Unused rows can be removed. Reserved or issued rows remain protected, and quantity cannot be lower than reserved/issued stock.</div><div className="project-material-editor">{materials.map((item,index)=><div key={item.id} className="project-material-row"><input aria-label="Item code" value={item.itemCode} onChange={(e)=>patch(index,{itemCode:e.target.value.toUpperCase()})}/><input required aria-label="Item name" value={item.itemName} onChange={(e)=>patch(index,{itemName:e.target.value})}/><input aria-label="Specification" value={item.specification??''} onChange={(e)=>patch(index,{specification:e.target.value})}/><input required aria-label="Required quantity" type="number" min={Math.max(item.reservedQty,item.issuedQty,0)} step="0.001" value={item.requiredQty} onChange={(e)=>patch(index,{requiredQty:Number(e.target.value)})}/><input required aria-label="Unit" value={item.unit} onChange={(e)=>patch(index,{unit:e.target.value})}/><button type="button" className="icon-btn bad" disabled={item.reservedQty>0||item.issuedQty>0} title={item.reservedQty>0||item.issuedQty>0?'Reserved or issued rows cannot be removed':'Remove material'} onClick={()=>setMaterials((rows)=>rows.filter((_,i)=>i!==index))}><Trash2 size={15}/></button></div>)}</div><button type="button" className="btn btn--small" onClick={()=>setMaterials((rows)=>[...rows,{id:crypto.randomUUID(),projectId:project.id,itemCode:'MANUAL',itemName:'New Material',requiredQty:1,reservedQty:0,issuedQty:0,unit:'Nos',shortageQty:1}])}><Plus size={14}/> Add Material</button><Field label="Change Reason (audit log)" wide><textarea required value={reason} onChange={(e)=>setReason(e.target.value)} placeholder="Why are these project material requirements being changed?"/></Field><div className="form-actions"><button type="button" className="btn" onClick={onClose}>Cancel</button><button className="btn btn--primary" disabled={saving||!reason.trim()||!materials.length}>{saving?'Saving...':'Save Material Requirements'}</button></div></form></Modal>;
}

export function InstallationForm({project,onClose}:{project:Project;onClose:()=>void}){
  const {data,saveInstallationAndIssueInvoice,saving}=useCrm(); const q=project.acceptedQuoteSnapshot; const [v,setV]=useState<InstallationDetails>({invoiceNo:'',invoiceDate:new Date().toISOString().slice(0,10),placeOfSupply:`${data?.settings.company.state??'Gujarat'} (${data?.settings.company.stateCode??'24'})`,taxTreatment:'inclusive',panelBrand:q.panelBrand,panelTechnology:q.panelTechnology,panelWattage:q.panelWattage,panelSerials:Array.from({length:q.panelQuantity},()=>''),inverterBrand:q.inverterBrand,inverterModel:q.inverterModel??'',inverterCapacityKw:q.inverterCapacityKw,inverterSerial:'',acdb:'',dcdb:'',acCable:'',dcCable:'',earthingCable:'',laCable:'',mountingStructure:q.structureType,earthingKit:'',lightningArrestor:'',monitoringSystem:'',additionalItems:''});
  const duplicates=v.panelSerials.filter((x,i,a)=>x&&a.indexOf(x)!==i); const changed=v.panelBrand!==q.panelBrand||v.panelWattage!==q.panelWattage||v.panelSerials.length!==q.panelQuantity;
  const invoiceDate=v.invoiceDate??new Date().toISOString().slice(0,10); const activeTaxRule=[...(data?.taxRules??[])].filter((rule)=>rule.active&&rule.effectiveFrom<=invoiceDate&&(!rule.effectiveTo||rule.effectiveTo>=invoiceDate)).sort((a,b)=>b.effectiveFrom.localeCompare(a.effectiveFrom))[0]; const taxPreview=activeTaxRule?calculateSplitGst(q.grandTotal,activeTaxRule,v.taxTreatment??'inclusive'):null;
  const extraFields: Array<[string,keyof InstallationDetails]>=[['ACDB','acdb'],['DCDB','dcdb'],['AC Cable','acCable'],['DC Cable','dcCable'],['Earthing Cable','earthingCable'],['LA Cable','laCable'],['Mounting Structure','mountingStructure'],['Earthing Kit','earthingKit'],['Lightning Arrestor','lightningArrestor'],['Online Monitoring System','monitoringSystem']];
  return <Modal title="Installation Materials and Tax Invoice" onClose={onClose} wide><form onSubmit={async(e)=>{e.preventDefault();await saveInstallationAndIssueInvoice(project.id,v);onClose();}}><div className="form-grid"><Field label="Invoice Number (editable)"><input value={v.invoiceNo??''} onChange={(e)=>setV({...v,invoiceNo:e.target.value})} placeholder={data?`${data.settings.invoiceNumbering.prefix}${String(data.settings.invoiceNumbering.nextNumber).padStart(data.settings.invoiceNumbering.padding,'0')} (automatic if blank)`:'Automatic if blank'}/><small>Leave blank to use the configured next number.</small></Field><Field label="Invoice Date"><input required type="date" value={v.invoiceDate??''} onChange={(e)=>setV({...v,invoiceDate:e.target.value})}/></Field><Field label="Place of Supply"><input required value={v.placeOfSupply??''} onChange={(e)=>setV({...v,placeOfSupply:e.target.value})}/></Field><Field label="Invoice GST Treatment"><select value={v.taxTreatment??'inclusive'} onChange={(e)=>setV({...v,taxTreatment:e.target.value as 'inclusive'|'exclusive'})}><option value="inclusive">GST Included in Quotation Amount</option><option value="exclusive">Add GST Above Quotation Amount</option></select><small>{v.taxTreatment==='exclusive'?'Quotation amount becomes taxable base; GST is added above it.':'GST is reverse-calculated inside the accepted quotation total.'}</small></Field><Field label="Panel Brand"><input required value={v.panelBrand} onChange={(e)=>setV({...v,panelBrand:e.target.value})}/></Field><Field label="Technology"><input required value={v.panelTechnology} onChange={(e)=>setV({...v,panelTechnology:e.target.value})}/></Field><Field label="Panel Wattage"><input required type="number" value={v.panelWattage} onChange={(e)=>setV({...v,panelWattage:Number(e.target.value)})}/></Field><Field label="Inverter Brand"><input required value={v.inverterBrand} onChange={(e)=>setV({...v,inverterBrand:e.target.value})}/></Field><Field label="Inverter Model"><input required value={v.inverterModel} onChange={(e)=>setV({...v,inverterModel:e.target.value})}/></Field><Field label="Inverter Capacity"><input required type="number" value={v.inverterCapacityKw} onChange={(e)=>setV({...v,inverterCapacityKw:Number(e.target.value)})}/></Field><Field label="Inverter Serial Number"><input required value={v.inverterSerial} onChange={(e)=>setV({...v,inverterSerial:e.target.value.trim()})}/></Field>{extraFields.map(([label,key])=><Field label={label} key={key}><input value={String(v[key]??'')} onChange={(e)=>setV({...v,[key]:e.target.value})}/></Field>)}</div>
    <section className="form-section"><div className="card__title"><h3>PV Module Serial Numbers ({v.panelSerials.length})</h3><button type="button" className="btn btn--small" onClick={()=>setV({...v,panelSerials:[...v.panelSerials,'']})}><Plus size={14}/> Add</button></div><div className="serial-grid">{v.panelSerials.map((serial,index)=><div key={index}><input required placeholder={`Panel ${index+1} serial`} value={serial} onChange={(e)=>setV({...v,panelSerials:v.panelSerials.map((x,i)=>i===index?e.target.value.trim():x)})}/><button type="button" aria-label={`Remove panel serial ${index+1}`} disabled={v.panelSerials.length===1} onClick={()=>setV({...v,panelSerials:v.panelSerials.filter((_,i)=>i!==index)})}><Trash2 size={14}/></button></div>)}</div></section>
    {changed&&<Field label="Material Change Reason"><textarea required value={v.overrideReason??''} onChange={(e)=>setV({...v,overrideReason:e.target.value})}/></Field>}{duplicates.length>0&&<div className="alert alert--error">Duplicate panel serial numbers: {duplicates.join(', ')}</div>}{taxPreview&&activeTaxRule?<div className="invoice-tax-preview"><strong>{activeTaxRule.name} · Accepted quotation {formatInr(q.grandTotal)} · {v.taxTreatment==='exclusive'?'GST added above':'GST included'}</strong>{taxPreview.lines.map((line)=><div key={line.lineType}><span>{line.lineType==='supply'?'Supply':'Installation'} {line.sharePercent}% · {line.hsnSac}</span><span>Taxable {formatInr(line.taxableValue)} · {activeTaxRule.intrastate?`CGST ${line.gstRate/2}% ${formatInr(line.cgst)} + SGST ${line.gstRate/2}% ${formatInr(line.sgst)}`:`IGST ${line.gstRate}% ${formatInr(line.igst)}`} · Line total {formatInr(line.grossAmount)}</span></div>)}<b>{v.taxTreatment==='exclusive'?`Final invoice total after GST: ${formatInr(taxPreview.gross)}`:`Final invoice total remains ${formatInr(taxPreview.gross)}`}</b></div>:<div className="alert alert--error">No active split GST rule exists for {formatDate(invoiceDate)}. Admin must publish one in Administration before issuing this invoice.</div>}<div className="alert alert--info">70/30 allocation and GST rates come from the effective-dated Admin rule. Confirm the applicable rate with your GST adviser before issuing.</div><div className="form-actions"><button type="button" className="btn" onClick={onClose}>Cancel</button><button className="btn btn--primary" disabled={saving||!activeTaxRule||duplicates.length>0||(changed&&!v.overrideReason?.trim())}>{saving?'Issuing...':'Save Installation and Issue Invoice'}</button></div></form></Modal>;
}
