import { useMemo, useState } from 'react';
import { CheckCircle2, Copy, Eye, FilePlus2, Plus, Send, Trash2, XCircle } from 'lucide-react';
import { Modal } from '../components/Modal';
import { Empty, Field, PageHeader, Status } from '../components/Ui';
import { useCrm } from '../lib/CrmContext';
import { calculateQuote, calculateSubsidyFromRules, formatInr } from '../services/calculations';
import type { Customer, Quotation, QuoteItem } from '../types/domain';
import { QuotationPrint } from './QuotationPrint';

const sourceStructure: Record<number, { pipe40: number; pipe60: number }> = {
  4:{pipe40:2,pipe60:3},5:{pipe40:3,pipe60:3},6:{pipe40:3,pipe60:4},7:{pipe40:3,pipe60:4},8:{pipe40:4,pipe60:4},9:{pipe40:4,pipe60:5},10:{pipe40:4,pipe60:5},11:{pipe40:5,pipe60:6},12:{pipe40:5,pipe60:6},13:{pipe40:6,pipe60:6},14:{pipe40:6,pipe60:6},15:{pipe40:6,pipe60:7},16:{pipe40:6,pipe60:7},17:{pipe40:6,pipe60:8},
};

const standardItems = (brand: string, tech: string, wattageLabel: string, qty: number): QuoteItem[] => {
  const structure = sourceStructure[qty];
  return [
  { id: crypto.randomUUID(), description: 'PV Module', brand, specification: `${wattageLabel} ${tech}`, quantity: qty, unit: 'Nos', rate: 0, taxRate: 0, selected: true },
  { id: crypto.randomUUID(), description: 'Grid Tie Inverter', brand: 'Polycab', specification: 'Capacity as selected', quantity: 1, unit: 'No', rate: 0, taxRate: 0, selected: true },
  { id: crypto.randomUUID(), description: 'GI Pipe 40 × 40', brand: 'Hot Dip Galvanized', specification: structure ? 'Source price-list structure quantity' : 'As per site design', quantity: structure?.pipe40 ?? 1, unit: structure ? 'Nos' : 'Lot', rate: 0, taxRate: 0, selected: true },
  { id: crypto.randomUUID(), description: 'GI Pipe 60 × 40', brand: 'Hot Dip Galvanized', specification: structure ? 'Source price-list structure quantity' : 'As per site design', quantity: structure?.pipe60 ?? 1, unit: structure ? 'Nos' : 'Lot', rate: 0, taxRate: 0, selected: true },
  { id: crypto.randomUUID(), description: 'AC Distribution Box', brand: 'Schneider / Approved', specification: 'Protection as per design', quantity: 1, unit: 'Set', rate: 0, taxRate: 0, selected: true },
  { id: crypto.randomUUID(), description: 'DC Distribution Box', brand: 'Schneider / Approved', specification: 'Protection as per design', quantity: 1, unit: 'Set', rate: 0, taxRate: 0, selected: true },
  { id: crypto.randomUUID(), description: 'AC Cable', brand: 'Polycab / Approved', specification: '4 sq.mm · 15 m + 15 m', quantity: 30, unit: 'm', rate: 0, taxRate: 0, selected: true },
  { id: crypto.randomUUID(), description: 'DC Cable', brand: 'Polycab / Approved', specification: '4 sq.mm', quantity: 40, unit: 'm', rate: 0, taxRate: 0, selected: true },
  { id: crypto.randomUUID(), description: 'Earthing Cable', brand: 'Approved', specification: '2.5 sq.mm', quantity: 40, unit: 'm', rate: 0, taxRate: 0, selected: true },
  { id: crypto.randomUUID(), description: 'Lightning Arrestor Cable', brand: 'Approved', specification: '16 sq.mm', quantity: 20, unit: 'm', rate: 0, taxRate: 0, selected: true },
  { id: crypto.randomUUID(), description: 'RPVC Pipe', brand: 'Approved', specification: '25 mm', quantity: 10, unit: 'Pcs', rate: 0, taxRate: 0, selected: true },
  { id: crypto.randomUUID(), description: 'Online Monitoring System', specification: 'Mobile application and remote monitoring', quantity: 1, unit: 'No', rate: 0, taxRate: 0, selected: true },
  { id: crypto.randomUUID(), description: 'Installation, Testing and Commissioning', specification: 'Complete rooftop EPC scope', quantity: 1, unit: 'Job', rate: 0, taxRate: 0, selected: true },
  ];
};

export function Quotations() {
  const { data, saveQuotation, setQuotationStatus, approveQuotationAndCreateProject, saving } = useCrm(); const [editing, setEditing] = useState<Quotation | 'new' | null>(null); const [preview, setPreview] = useState<Quotation | null>(null); const [filter, setFilter] = useState('all');
  if (!data) return null;
  const list = filter === 'all' ? data.quotations : data.quotations.filter((q) => q.status === filter); const customer = (id: string) => data.customers.find((c) => c.id === id);
  const canApprove = data.profile.role !== 'dealer'; const statusTone = (s: string) => s === 'approved' || s === 'project_created' ? 'good' : s === 'rejected' ? 'bad' : ['sent','pending'].includes(s) ? 'warn' : 'neutral';
  const change = async (q: Quotation, status: Quotation['status']) => { const reason = status === 'rejected' ? window.prompt('Rejection reason (required)') ?? '' : ''; if (status === 'rejected' && !reason.trim()) return; await setQuotationStatus(q.id, status, reason); };
  const approve = async (q: Quotation) => { if (!window.confirm(`Approve ${q.quoteNo} and create its project now?`)) return; await approveQuotationAndCreateProject(q.id); };
  return <>
    <PageHeader title="Quotations" subtitle="Exact price snapshots, controlled revisions and confidential customer copies." actions={<button className="btn btn--primary" onClick={() => setEditing('new')} disabled={!data.customers.length}><Plus size={17} /> New Quotation</button>} />
    <div className="toolbar"><select aria-label="Quotation status filter" value={filter} onChange={(e) => setFilter(e.target.value)}><option value="all">All statuses</option>{['draft','sent','pending','approved','rejected','project_created'].map((s) => <option key={s}>{s}</option>)}</select></div>
    <section className="card table-card">{list.length ? <table><thead><tr><th>Reference</th><th>Customer</th><th>System</th><th>Value</th><th>Status</th><th>Actions</th></tr></thead><tbody>{list.map((q) => <tr key={q.id}><td><strong>{q.quoteNo}</strong><small>Revision {q.versionNo}</small></td><td>{customer(q.customerId)?.fullName ?? 'Missing customer'}</td><td>{q.dcCapacityKw.toFixed(3)} kW<small>{q.panelBrand} {q.panelTechnology} · {q.panelWattageLabel ?? `${q.panelWattage} Wp`}</small></td><td><strong>{formatInr(q.grandTotal)}</strong><small>GST included</small></td><td><Status tone={statusTone(q.status)}>{q.status.replace('_',' ')}</Status></td><td><div className="row-actions">
      <button className="icon-btn" title="Preview" onClick={() => setPreview(q)}><Eye size={16} /></button>
      {q.status === 'draft' && <button className="icon-btn" title="Edit draft" onClick={() => setEditing(q)}><FilePlus2 size={16} /></button>}
      {q.status === 'draft' && <button className="icon-btn" title="Mark sent" onClick={() => void change(q, 'sent')}><Send size={16} /></button>}
      {canApprove && ['sent','pending','approved'].includes(q.status) && <button className="icon-btn good" title="Approve and create project" onClick={() => void approve(q)}><CheckCircle2 size={16} /></button>}
      {canApprove && !['rejected','project_created'].includes(q.status) && <button className="icon-btn bad" title="Reject" onClick={() => void change(q, 'rejected')}><XCircle size={16} /></button>}
      {!['draft','project_created'].includes(q.status) && <button className="icon-btn" title="Create revision" onClick={() => setEditing({ ...q, id: crypto.randomUUID(), versionNo: q.versionNo + 1, status: 'draft', createdAt: new Date().toISOString(), approvedAt: null, sentAt: null, rejectedAt: null })}><Copy size={16} /></button>}
    </div></td></tr>)}</tbody></table> : <Empty title="No quotations" detail="Create a quotation after adding a customer." />}</section>
    {editing && <QuoteForm initial={editing === 'new' ? undefined : editing} customers={data.customers} onClose={() => setEditing(null)} saving={saving} onSave={async (quote) => { await saveQuotation(quote); setEditing(null); }} />}
    {preview && customer(preview.customerId) && <QuotationPrint quote={preview} customer={customer(preview.customerId)!} onClose={() => setPreview(null)} />}
  </>;
}

function QuoteForm({ initial, customers, onClose, onSave, saving }: { initial?: Quotation; customers: Customer[]; onClose: () => void; onSave: (q: Quotation) => Promise<void>; saving: boolean }) {
  const { data } = useCrm(); const visibleCustomers = data?.profile.role === 'dealer' ? customers.filter((c) => c.dealerId === data.profile.dealerId) : customers;
  const [quoteNo, setQuoteNo] = useState(initial?.quoteNo ?? ''); const [customerId, setCustomerId] = useState(initial?.customerId ?? visibleCustomers[0]?.id ?? ''); const [systemType, setSystemType] = useState<Quotation['systemType']>(initial?.systemType ?? 'On-grid'); const [dcrType, setDcrType] = useState<Quotation['dcrType']>(initial?.dcrType ?? 'DCR');
  const [tech, setTech] = useState<Quotation['panelTechnology']>(initial?.panelTechnology ?? 'TOPCon'); const [brand, setBrand] = useState(initial?.panelBrand ?? 'WAAREE'); const [wattage, setWattage] = useState(initial?.panelWattage ?? 580); const [qty, setQty] = useState(initial?.panelQuantity ?? 4);
  const priceMatch = useMemo(() => data?.priceRows.find((r) => r.panelTechnology === tech && r.panelBrand === brand && r.panelWattage === wattage && r.panelQuantity === qty), [brand, data?.priceRows, qty, tech, wattage]);
  const suggested = priceMatch?.price ?? initial?.suggestedPrice ?? 0; const [finalOverride, setFinalOverride] = useState<number | null>(initial?.grandTotal ?? null); const finalPrice = finalOverride ?? suggested; const [overrideReason, setOverrideReason] = useState(initial?.priceOverrideReason ?? '');
  const [inverterBrand, setInverterBrand] = useState(initial?.inverterBrand ?? 'Polycab'); const [inverterModel, setInverterModel] = useState(initial?.inverterModel ?? ''); const [inverterKw, setInverterKw] = useState(initial?.inverterCapacityKw ?? 3); const [structureType, setStructureType] = useState(initial?.structureType ?? 'Hot Dip GI');
  const [items, setItems] = useState<QuoteItem[]>(initial?.items ?? standardItems(brand, tech, initial?.panelWattageLabel ?? `${wattage} Wp`, qty)); const [paymentTerms, setPaymentTerms] = useState(initial?.paymentTerms ?? data?.settings.paymentTerms ?? ''); const [warrantyTerms, setWarrantyTerms] = useState(initial?.warrantyTerms ?? data?.settings.warrantyTerms ?? ''); const [validityDays, setValidityDays] = useState(initial?.validityDays ?? data?.settings.quotationValidityDays ?? 15); const [notes, setNotes] = useState(initial?.notes ?? data?.settings.quotationNotes ?? '');
  const [dealerId, setDealerId] = useState(initial?.dealerId ?? visibleCustomers.find((c) => c.id === customerId)?.dealerId ?? ''); const [commissionType, setCommissionType] = useState<'fixed'|'percentage'>('fixed'); const [commissionValue, setCommissionValue] = useState(initial?.dealerCommission ?? 0);
  const customer = visibleCustomers.find((c) => c.id === customerId); const calc = calculateQuote({ panelWattage: wattage, panelQuantity: qty, basePrice: finalPrice, extraItems: [], discount: 0, taxMode: 'inclusive', taxRate: initial?.taxRate ?? 0 });
  const brands = [...new Set(data?.priceRows.filter((r) => r.panelTechnology === tech).map((r) => r.panelBrand))]; const wattages = [...new Set(data?.priceRows.filter((r) => r.panelTechnology === tech && r.panelBrand === brand).map((r) => r.panelWattage))]; const configurationRows = data?.priceRows.filter((r) => r.panelTechnology === tech && r.panelBrand === brand && r.panelWattage === wattage).sort((a,b) => a.panelQuantity-b.panelQuantity) ?? [];
  const chooseFirst = (technology: Quotation['panelTechnology'], nextBrand?: string) => {
    const first = data?.priceRows.find((r) => r.panelTechnology === technology && (!nextBrand || r.panelBrand === nextBrand));
    if (!first) return;
    setBrand(first.panelBrand); setWattage(first.panelWattage); setQty(first.panelQuantity); setFinalOverride(null);
  };
  const submit = async (e: React.FormEvent) => { e.preventDefault(); if (!customer || !priceMatch) return; if (finalPrice !== suggested && !overrideReason.trim()) return;
    const wattageLabel = priceMatch.panelWattageLabel ?? `${wattage} Wp`;
    const structure = sourceStructure[qty];
    const normalizedItems = items.map((item) => item.description === 'PV Module'
      ? { ...item, brand, specification: `${wattageLabel} ${tech}`, quantity: qty }
      : item.description === 'Grid Tie Inverter'
        ? { ...item, brand: inverterBrand, specification: `${inverterModel} ${inverterKw} kW`.trim() }
        : item.description === 'GI Pipe 40 × 40' && structure
          ? { ...item, quantity: structure.pipe40, unit: 'Nos', specification: 'Source price-list structure quantity' }
          : item.description === 'GI Pipe 60 × 40' && structure
            ? { ...item, quantity: structure.pipe60, unit: 'Nos', specification: 'Source price-list structure quantity' }
            : item);
    const dealerCommission = dealerId ? (commissionType === 'percentage' ? finalPrice * commissionValue / 100 : commissionValue) : 0;
    await onSave({ id: initial?.id ?? crypto.randomUUID(), quoteNo: quoteNo.trim(), customerId, versionNo: initial?.versionNo ?? 1, status: initial?.status ?? 'draft', systemType, dcrType, scheme: 'PM Surya Ghar', panelTechnology: tech, panelBrand: brand, panelWattage: wattage, panelWattageLabel: wattageLabel, panelQuantity: qty, dcCapacityKw: priceMatch.capacityKw, inverterBrand, inverterModel, inverterCapacityKw: inverterKw, structureType, items: normalizedItems, suggestedPrice: suggested, priceOverrideReason: finalPrice !== suggested ? overrideReason : '', basePrice: finalPrice, discount: 0, taxMode: 'inclusive', taxRate: initial?.taxRate ?? 0, taxableValue: calc.taxableValue, taxAmount: calc.taxAmount, roundOff: calc.roundOff, grandTotal: finalPrice, subsidy: calculateSubsidyFromRules(customer.customerType, priceMatch.capacityKw, data?.subsidyRules ?? []), dealerId: dealerId || null, dealerCommission, internalCost: initial?.internalCost ?? 0, paymentTerms, warrantyTerms, validityDays, notes, createdAt: initial?.createdAt ?? new Date().toISOString(), approvedAt: initial?.approvedAt, sentAt: initial?.sentAt, rejectedAt: initial?.rejectedAt, priceSnapshot: { priceRowId: priceMatch.id, technology: tech, brand, wattage, wattageLabel, panelWattageMin: priceMatch.panelWattageMin, panelWattageMax: priceMatch.panelWattageMax, panelQuantity: qty, capacityKw: priceMatch.capacityKw, suggestedPrice: suggested, finalPrice, gstIncluded: true, sourceDocument: priceMatch.sourceDocument, capturedAt: new Date().toISOString() } });
  };
  return <Modal title={initial ? `Quotation Revision ${initial.versionNo}` : 'New Quotation'} onClose={onClose} wide><form onSubmit={submit}><div className="form-grid">
    <Field label="Quotation Number (editable)"><input value={quoteNo} readOnly={Boolean(initial?.quoteNo)} onChange={(e)=>setQuoteNo(e.target.value)} placeholder={data ? `${data.settings.quotationNumbering.prefix}${String(data.settings.quotationNumbering.nextNumber).padStart(data.settings.quotationNumbering.padding,'0')} (automatic if blank)` : 'Automatic if blank'} /><small>{initial?.quoteNo ? 'Existing quotation number remains locked across revisions.' : 'Leave blank for the configured automatic number, or enter your next manual number.'}</small></Field><Field label="Customer"><select required value={customerId} onChange={(e) => setCustomerId(e.target.value)}>{visibleCustomers.map((c) => <option value={c.id} key={c.id}>{c.fullName} · {c.mobile}</option>)}</select></Field><Field label="System Type"><select value={systemType} onChange={(e) => setSystemType(e.target.value as Quotation['systemType'])}>{['On-grid','Off-grid','Hybrid'].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="DCR / Non-DCR"><select value={dcrType} onChange={(e) => setDcrType(e.target.value as Quotation['dcrType'])}><option>DCR</option><option>Non-DCR</option></select></Field>
    <Field label="Panel Technology"><select value={tech} onChange={(e) => { const t=e.target.value as Quotation['panelTechnology']; setTech(t); chooseFirst(t); }}><option>Bifacial</option><option>TOPCon</option></select></Field><Field label="Panel Brand"><select value={brand} onChange={(e) => { const next=e.target.value; chooseFirst(tech,next); }}>{brands.map((x)=><option key={x}>{x}</option>)}</select></Field><Field label="Panel Wattage / Source Range"><select value={wattage} onChange={(e)=>{const next=Number(e.target.value);setWattage(next);const first=data?.priceRows.find((r)=>r.panelTechnology===tech&&r.panelBrand===brand&&r.panelWattage===next);if(first)setQty(first.panelQuantity);setFinalOverride(null);}}>{wattages.map((x)=>{const row=data?.priceRows.find((r)=>r.panelTechnology===tech&&r.panelBrand===brand&&r.panelWattage===x);return <option key={x} value={x}>{row?.panelWattageLabel ?? `${x} Wp`}</option>;})}</select></Field><Field label="Exact PDF Configuration"><select value={qty} onChange={(e)=>{setQty(Number(e.target.value));setFinalOverride(null);}}>{configurationRows.map((row)=><option key={row.panelQuantity} value={row.panelQuantity}>{row.panelQuantity} panels · {row.capacityKw.toFixed(3)} kW</option>)}</select></Field><Field label="Exact DC Capacity"><input readOnly value={priceMatch ? `${priceMatch.capacityKw.toFixed(3)} kW` : 'No exact configuration'} /></Field>
    <Field label="Inverter Brand"><select value={inverterBrand} onChange={(e)=>setInverterBrand(e.target.value)}>{['KSOLE','Solaryan','Suryyan','Polycab'].map((x)=><option key={x}>{x}</option>)}</select></Field><Field label="Inverter Model"><input value={inverterModel} onChange={(e)=>setInverterModel(e.target.value)} /></Field><Field label="Inverter Capacity (kW)"><input type="number" step="0.1" value={inverterKw} onChange={(e)=>setInverterKw(Number(e.target.value))} /></Field><Field label="Structure Type"><input value={structureType} onChange={(e)=>setStructureType(e.target.value)} /></Field>
    <Field label="Suggested Price (GST included)"><input readOnly value={suggested} /></Field><Field label="Final Customer Price (GST included)"><input required type="number" min="1" value={finalPrice} onChange={(e)=>setFinalOverride(Number(e.target.value))} /></Field>{finalPrice !== suggested && <Field label="Price Override Reason"><textarea required value={overrideReason} onChange={(e)=>setOverrideReason(e.target.value)} /></Field>}
    {data?.profile.role !== 'dealer' && <><Field label="Dealer (optional)"><select value={dealerId ?? ''} onChange={(e)=>setDealerId(e.target.value)}><option value="">No dealer</option>{data?.dealers.map((d)=><option value={d.id} key={d.id}>{d.name}</option>)}</select></Field>{dealerId && <Field label="Dealer Commission"><div className="compound"><select value={commissionType} onChange={(e)=>setCommissionType(e.target.value as 'fixed'|'percentage')}><option value="fixed">Fixed ₹</option><option value="percentage">Percentage %</option></select><input type="number" min="0" value={commissionValue} onChange={(e)=>setCommissionValue(Number(e.target.value))} /></div></Field>}</>}
    <Field label="Validity (days)"><input type="number" min="1" value={validityDays} onChange={(e)=>setValidityDays(Number(e.target.value))} /></Field><Field label="Payment Terms"><textarea value={paymentTerms} onChange={(e)=>setPaymentTerms(e.target.value)} /></Field><Field label="Warranty Terms"><textarea value={warrantyTerms} onChange={(e)=>setWarrantyTerms(e.target.value)} /></Field><Field label="Notes"><textarea value={notes} onChange={(e)=>setNotes(e.target.value)} /></Field>
  </div><section className="form-section"><div className="card__title"><div><h3>Customer-facing BOM</h3><p>Every row stays editable until the quotation is approved.</p></div><button type="button" className="btn btn--small" onClick={() => setItems((v)=>[...v,{id:crypto.randomUUID(),description:'Additional Item',quantity:1,unit:'Lot',rate:0,taxRate:0,selected:true}])}><Plus size={14} /> Add Item</button></div>{items.map((item,index)=><div className="bom-editor" key={item.id}><input aria-label="Include item" type="checkbox" checked={item.selected} onChange={(e)=>setItems((v)=>v.map((x,i)=>i===index?{...x,selected:e.target.checked}:x))}/><input aria-label="Description" value={item.description} onChange={(e)=>setItems((v)=>v.map((x,i)=>i===index?{...x,description:e.target.value}:x))}/><input aria-label="Brand" value={item.brand??''} placeholder="Brand" onChange={(e)=>setItems((v)=>v.map((x,i)=>i===index?{...x,brand:e.target.value}:x))}/><input aria-label="Specification" value={item.specification??''} placeholder="Specification" onChange={(e)=>setItems((v)=>v.map((x,i)=>i===index?{...x,specification:e.target.value}:x))}/><input aria-label="Quantity" type="number" min="0.001" step="0.001" value={item.quantity} onChange={(e)=>setItems((v)=>v.map((x,i)=>i===index?{...x,quantity:Number(e.target.value)}:x))}/><input aria-label="Unit" value={item.unit} placeholder="Unit" onChange={(e)=>setItems((v)=>v.map((x,i)=>i===index?{...x,unit:e.target.value}:x))}/><button type="button" className="icon-btn bad" title="Remove material row" onClick={()=>setItems((v)=>v.filter((_,i)=>i!==index))}><Trash2 size={15}/></button></div>)}</section>
    {!priceMatch && <div className="alert alert--error">No exact active price configuration exists. Select another combination or ask Admin to publish it.</div>}<div className="quote-total"><span>GST included · subsidy shown separately</span><strong>Gross Total {formatInr(finalPrice)}</strong></div><div className="form-actions"><button type="button" className="btn" onClick={onClose}>Cancel</button><button disabled={saving||!priceMatch||(finalPrice!==suggested&&!overrideReason.trim())} className="btn btn--primary">{saving?'Saving...':'Save Quotation'}</button></div></form></Modal>;
}
