import { useMemo, useState } from 'react';
import { Download, Plus } from 'lucide-react';
import { Empty, Field, PageHeader, Status } from '../components/Ui';
import { Modal } from '../components/Modal';
import { useCrm } from '../lib/CrmContext';
import { downloadWorkbook } from '../services/excel';
import { formatDate, formatInr } from '../services/calculations';
import { supabase } from '../lib/supabase';
import type { PriceRow } from '../types/domain';

type ReportRow = Record<string, string | number>;

export function Reports() {
  const { data } = useCrm(); const [report, setReport] = useState('Customer Report'); const [district, setDistrict] = useState(''); const [status, setStatus] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState('');
  const reports = useMemo(() => data ? buildReports(data) : {}, [data]);
  if (!data || data.profile.role !== 'admin') return <Empty title="Access denied" detail="Global reports and exports are restricted to Admin users." />;
  const filtered = (reports[report] ?? []).filter((row) => (!district || row.District === district) && (!status || row.Status === status || row.Stage === status) && (!from || String(row.Date ?? row['Created Date'] ?? '') >= from) && (!to || String(row.Date ?? row['Created Date'] ?? '') <= to));
  const columns = Object.keys(filtered[0] ?? reports[report]?.[0] ?? {}).map((key) => ({ header: key, key, total: /Amount|Value|Capacity|Paid|Outstanding|Quantity/.test(key), width: /Name|Address|Description/.test(key) ? 28 : 16 }));
  return <>
    <PageHeader title="Reports and Excel Exports" subtitle="Admin-only operational, financial, inventory and audit workbooks with filters and formatted totals." actions={<button className="btn btn--primary" disabled={!filtered.length} onClick={() => downloadWorkbook(`${report.replace(/\s+/g,'-').toLowerCase()}.xlsx`, report, filtered, columns)}><Download size={16} /> Export .xlsx</button>} />
    <section className="card"><div className="filter-grid"><Field label="Report"><select value={report} onChange={(e) => setReport(e.target.value)}>{Object.keys(reports).map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="From Date"><input type="date" value={from} onChange={(e) => setFrom(e.target.value)} /></Field><Field label="To Date"><input type="date" value={to} onChange={(e) => setTo(e.target.value)} /></Field><Field label="District"><select value={district} onChange={(e) => setDistrict(e.target.value)}><option value="">All districts</option>{data.districts.map((x) => <option key={x.id}>{x.name}</option>)}</select></Field><Field label="Status / Stage"><input value={status} placeholder="Optional exact filter" onChange={(e) => setStatus(e.target.value)} /></Field></div></section>
    <section className="card table-card report-preview"><div className="card__title"><h2>{report}</h2><Status tone="info">{filtered.length} rows</Status></div>{filtered.length ? <table><thead><tr>{Object.keys(filtered[0]!).map((x) => <th key={x}>{x}</th>)}</tr></thead><tbody>{filtered.slice(0, 200).map((row, index) => <tr key={index}>{Object.values(row).map((value, i) => <td key={i}>{typeof value === 'number' && /amount|value|paid|outstanding/i.test(Object.keys(row)[i] ?? '') ? formatInr(value) : String(value)}</td>)}</tr>)}</tbody></table> : <Empty title="No matching records" detail="Change the filters or select another report." />}</section>
  </>;
}

export function Pricing() {
  const { data, refresh } = useCrm(); const [editing, setEditing] = useState<Partial<PriceRow> | null>(null); const [error, setError] = useState('');
  if (!data || data.profile.role !== 'admin') return <Empty title="Access denied" detail="Only Admin can manage price lists." />;
  return <><PageHeader title="Price List" subtitle="Exact GST-inclusive configurations are effective-dated. Publishing a change creates a new version and never changes old quotations." actions={<button className="btn btn--primary" onClick={() => setEditing({ panelBrand: 'WAAREE', panelTechnology: 'TOPCon', panelWattage: 580, panelQuantity: 4, capacityKw: 2.32, price: 0, effectiveFrom: new Date().toISOString().slice(0,10), sourceDocument: 'Manual Admin Entry', active: true })}><Plus size={16} /> New Price Row</button>} />{error && <div className="alert alert--error">{error}</div>}
    <section className="card table-card"><table><thead><tr><th>Brand / Technology</th><th>Source Wattage Range</th><th>Panels</th><th>Exact DC Capacity</th><th>GST-Inclusive Price</th><th>Effective</th><th>Source</th><th>Action</th></tr></thead><tbody>{data.priceRows.map((row) => <tr key={row.id ?? `${row.panelBrand}-${row.panelWattage}-${row.panelQuantity}`}><td><strong>{row.panelBrand}</strong><small>{row.panelTechnology}</small></td><td>{row.panelWattageLabel ?? `${row.panelWattage} Wp`}</td><td>{row.panelQuantity}</td><td>{row.capacityKw.toFixed(3)} kW</td><td>{formatInr(row.price)}<small>GST included</small></td><td>{formatDate(row.effectiveFrom)}</td><td>{row.sourceDocument}</td><td><button className="btn btn--small" onClick={() => setEditing(row)}>New Version</button></td></tr>)}</tbody></table></section>
    {editing && <Modal title="Publish Price Configuration" onClose={() => setEditing(null)}><form onSubmit={async (e) => { e.preventDefault(); setError(''); const { error: saveError } = await supabase!.rpc('publish_price_row', { p_row: editing }); if (saveError) setError(saveError.message); else { await refresh(); setEditing(null); } }}><div className="form-grid"><Field label="Panel Brand"><input required value={editing.panelBrand ?? ''} onChange={(e) => setEditing({ ...editing, panelBrand: e.target.value.toUpperCase() })} /></Field><Field label="Technology"><select value={editing.panelTechnology} onChange={(e) => setEditing({ ...editing, panelTechnology: e.target.value as PriceRow['panelTechnology'] })}><option>Bifacial</option><option>TOPCon</option></select></Field><Field label="Wattage Used for Matching"><input required type="number" value={editing.panelWattage ?? ''} onChange={(e) => setEditing({ ...editing, panelWattage: Number(e.target.value) })} /></Field><Field label="Display Range / Label"><input required value={editing.panelWattageLabel ?? `${editing.panelWattage ?? ''} Wp`} onChange={(e) => setEditing({ ...editing, panelWattageLabel: e.target.value })} /></Field><Field label="Panel Quantity"><input required type="number" value={editing.panelQuantity ?? ''} onChange={(e) => setEditing({ ...editing, panelQuantity: Number(e.target.value) })} /></Field><Field label="Exact DC Capacity from Source"><input required type="number" step="0.001" value={editing.capacityKw ?? ''} onChange={(e) => setEditing({ ...editing, capacityKw: Number(e.target.value) })} /></Field><Field label="GST-Inclusive Gross Price"><input required type="number" min="1" value={editing.price ?? ''} onChange={(e) => setEditing({ ...editing, price: Number(e.target.value) })} /></Field><Field label="Expected Subsidy (reference)"><input type="number" min="0" value={editing.expectedSubsidy ?? ''} onChange={(e) => setEditing({ ...editing, expectedSubsidy: Number(e.target.value) || undefined })} /></Field><Field label="Effective From"><input required type="date" value={editing.effectiveFrom} onChange={(e) => setEditing({ ...editing, effectiveFrom: e.target.value })} /></Field><Field label="Source Document"><input required value={editing.sourceDocument ?? ''} onChange={(e) => setEditing({ ...editing, sourceDocument: e.target.value })} /></Field></div><div className="alert alert--info">The gross price already includes GST. Exact capacity is kept separately because the source PDF contains wattage ranges.</div><div className="form-actions"><button type="button" className="btn" onClick={() => setEditing(null)}>Cancel</button><button className="btn btn--primary">Publish New Version</button></div></form></Modal>}
  </>;
}

function buildReports(data: NonNullable<ReturnType<typeof useCrm>['data']>): Record<string, ReportRow[]> {
  const customer = (id: string) => data.customers.find((x) => x.id === id); const dealer = (id?: string | null) => data.dealers.find((x) => x.id === id);
  const projectRows = data.projects.map((p) => ({ Project: p.projectNo, Customer: customer(p.customerId)?.fullName ?? '', District: p.district, Stage: p.stage, 'Capacity kW': p.acceptedQuoteSnapshot.dcCapacityKw, 'Gross Value': p.acceptedQuoteSnapshot.grandTotal, Date: p.createdAt.slice(0,10) }));
  const commissionRows = data.commissions.map((c) => ({ Dealer: dealer(c.dealerId)?.name ?? '', Customer: customer(c.customerId)?.fullName ?? '', District: dealer(c.dealerId)?.district ?? '', 'Total Amount': c.totalCommission, Paid: c.amountPaid, Outstanding: c.totalCommission - c.amountPaid, Status: c.status, Date: c.createdAt.slice(0,10) }));
  return {
    'Customer Report': data.customers.map((c) => ({ 'Customer Number': c.customerNo, Name: c.fullName, Mobile: c.mobile, 'Consumer Number': c.consumerNumber ?? '', District: c.district, Category: c.customerType, Dealer: dealer(c.dealerId)?.name ?? '', Status: c.leadStatus, 'Created Date': c.createdAt.slice(0,10) })),
    'Quotation Report': data.quotations.map((q) => ({ Quotation: q.quoteNo, Customer: customer(q.customerId)?.fullName ?? '', District: customer(q.customerId)?.district ?? '', Brand: q.panelBrand, Technology: q.panelTechnology, 'Capacity kW': q.dcCapacityKw, 'Gross Value': q.grandTotal, Status: q.status, Date: q.createdAt.slice(0,10) })),
    'Quotation Status Report': data.quotations.map((q) => ({ Quotation: q.quoteNo, Customer: customer(q.customerId)?.fullName ?? '', District: customer(q.customerId)?.district ?? '', Status: q.status, Revision: q.versionNo, Date: q.createdAt.slice(0,10) })),
    'Project Stage Report': projectRows, 'District-wise Project Report': projectRows, 'Installed Capacity Report': projectRows.filter((x) => ['installation_done','inspection_pending','inspection_done','meter_pending','meter_done','commissioning_done','subsidy_pending','subsidy_passed','handover_completed','project_closed'].includes(x.Stage)),
    'Dealer Commission Summary': commissionRows, 'Outstanding Dealer Commission Report': commissionRows.filter((x) => x.Outstanding > 0),
    'Dealer Commission Payment Ledger': data.commissions.flatMap((c) => c.payments.map((p) => ({ Dealer: dealer(c.dealerId)?.name ?? '', Date: p.paymentDate, Amount: p.amount, Mode: p.mode, Reference: p.referenceNo ?? '', Status: c.status }))),
    'Inventory Stock Report': data.inventory.map((x) => ({ Item: x.itemName, Brand: x.brand ?? '', District: x.warehouseDistrict ?? '', 'On Hand Quantity': x.onHand, 'Reserved Quantity': x.reserved, 'Available Quantity': x.available, 'Average Rate': x.averageRate, Status: x.available <= x.reorderLevel ? 'Low Stock' : 'Available' })),
    'Inventory Transaction Report': data.stockTransactions.map((x) => ({ Date: x.occurredAt.slice(0,10), Item: data.inventory.find((i) => i.id === x.inventoryItemId)?.itemName ?? '', Type: x.transactionType, Quantity: x.quantity, Reference: x.referenceNo ?? '', Reason: x.reason ?? '' })),
    'Low Stock/Shortage Report': data.inventory.filter((x) => x.available <= x.reorderLevel).map((x) => ({ Item: x.itemName, District: x.warehouseDistrict ?? '', 'Available Quantity': x.available, 'Reorder Level': x.reorderLevel, Status: 'Low Stock' })),
    'Purchase Invoice Report': data.purchaseInvoices.map((x) => ({ 'Invoice Number': x.invoiceNumber, Vendor: x.vendorName, GSTIN: x.vendorGstin ?? '', Date: x.invoiceDate, Amount: x.grossTotal, 'Source File': x.storagePath ?? '', Status: 'Posted' })),
    'Customer Invoice Report': [
      ...data.invoices.map((x) => ({ Invoice: x.invoiceNo, 'Source Quotation': data.projects.find((project)=>project.id===x.projectId)?.acceptedQuoteSnapshot.quoteNo ?? '', Customer: customer(x.customerId)?.fullName ?? '', District: customer(x.customerId)?.district ?? '', Date: x.invoiceDate, Amount: x.grandTotal, Status: x.status, Source:'CRM Project' })),
      ...data.manualInvoices.map((x) => ({ Invoice:x.invoiceNo,'Source Quotation':x.legacyQuoteNo,Customer:x.customerName,District:x.district,Date:x.invoiceDate,Amount:x.grandTotal,Status:x.status,Source:'Manual Invoice' })),
    ],
    'Loan Status Report': projectRows.filter((x) => x.Stage.startsWith('loan_')), 'PGVCL Inspection Status Report': projectRows.filter((x) => x.Stage.includes('inspection')), 'Meter Installation Status Report': projectRows.filter((x) => x.Stage.includes('meter')), 'Subsidy Status Report': projectRows.filter((x) => x.Stage.includes('subsidy')),
    'User Activity/Audit Report': data.auditLogs.map((x) => ({ Date: x.createdAt.slice(0,10), Actor: x.actorName ?? '', Action: x.action, Entity: x.entityType, Reason: x.reason ?? '', Status: 'Recorded' })),
  };
}
