import JSZip from 'npm:jszip@3.10.1';
import { z } from 'npm:zod@3.25.74';
import { authorisedProfile, cors, json } from '../_shared/security.ts';

const fileSchema=z.object({name:z.string().min(1),type:z.string(),data:z.string().min(1)});type FilePayload=z.infer<typeof fileSchema>;const requestSchema=z.object({kind:z.enum(['customer','vendor_invoice']),files:z.array(fileSchema).min(1).max(40)});
const customerJson={type:'object',additionalProperties:false,required:['documentType','fields','warnings'],properties:{documentType:{type:'string'},fields:{type:'object',additionalProperties:false,required:['fullName','mobile','address','villageCity','consumerNumber','discom','sanctionedLoadKw','meterType','pan','bank'],properties:Object.fromEntries(['fullName','mobile','address','villageCity','consumerNumber','discom','sanctionedLoadKw','meterType','pan','bank'].map((key)=>[key,{type:'object',additionalProperties:false,required:['value','confidence','source'],properties:{value:{type:['string','number','null']},confidence:{type:'number',minimum:0,maximum:1},source:{type:'string'}}}]))},warnings:{type:'array',items:{type:'string'}}}};
const invoiceJson={type:'object',additionalProperties:false,required:['vendorName','gstin','invoiceNumber','invoiceDate','fileHash','total','rows'],properties:{vendorName:{type:'string'},gstin:{type:['string','null']},invoiceNumber:{type:'string'},invoiceDate:{type:'string'},fileHash:{type:'string'},total:{type:'number'},rows:{type:'array',items:{type:'object',additionalProperties:false,required:['description','brand','model','hsn','quantity','unit','rate','tax','total','confidence','source'],properties:{description:{type:'string'},brand:{type:['string','null']},model:{type:['string','null']},hsn:{type:['string','null']},quantity:{type:'number'},unit:{type:'string'},rate:{type:'number'},tax:{type:'number'},total:{type:'number'},confidence:{type:'number'},source:{type:'string'}}}}}};

function geminiSchema(value:any):any{if(Array.isArray(value))return value.map(geminiSchema);if(!value||typeof value!=='object')return value;const result:any={};for(const[key,item]of Object.entries(value)){if(key==='additionalProperties')continue;if(key==='type'&&Array.isArray(item)){result.type=item.find((entry)=>entry!=='null')??'string';result.nullable=item.includes('null');}else result[key]=geminiSchema(item);}return result;}

async function extractWithGemini(prompt:string,files:FilePayload[],schema:any){
  const apiKey=Deno.env.get('GEMINI_API_KEY');if(!apiKey)return null;
  const model=Deno.env.get('GEMINI_MODEL')??'gemini-2.5-flash';
  const parts:any[]=[{text:prompt}];for(const file of files)parts.push({inline_data:{mime_type:file.type||'application/octet-stream',data:file.data}});
  const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(apiKey)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts}],generationConfig:{temperature:0,responseMimeType:'application/json',responseJsonSchema:geminiSchema(schema)}})});
  if(!response.ok){const failure=await response.json().catch(()=>({})) as{error?:{message?:string}};throw new Error(failure.error?.message??`Gemini returned ${response.status}. Check GEMINI_API_KEY, model access and quota.`);}
  const raw=await response.json();const text=raw.candidates?.[0]?.content?.parts?.find((part:any)=>typeof part.text==='string')?.text;if(!text)throw new Error('Gemini returned no structured extraction.');return{extraction:JSON.parse(text),provider:'gemini'};
}

async function extractWithOpenAi(prompt:string,files:FilePayload[],schema:any,name:string){
  const apiKey=Deno.env.get('OPENAI_API_KEY');if(!apiKey)return null;const content:any[]=[{type:'input_text',text:prompt}];for(const file of files){const url=`data:${file.type||'application/octet-stream'};base64,${file.data}`;content.push(file.type.startsWith('image/')?{type:'input_image',image_url:url}:{type:'input_file',filename:file.name,file_data:url});}
  const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:Deno.env.get('OPENAI_MODEL')??'gpt-5-mini',input:[{role:'user',content}],text:{format:{type:'json_schema',name,strict:true,schema}}})});if(!response.ok){const failure=await response.json().catch(()=>({})) as{error?:{message?:string}};throw new Error(failure.error?.message??`OpenAI returned ${response.status}. Check API key, model access and billing credit.`);}const raw=await response.json();const text=raw.output?.flatMap((output:any)=>output.content??[]).find((part:any)=>part.type==='output_text')?.text;if(!text)throw new Error('OpenAI returned no structured extraction.');return{extraction:JSON.parse(text),provider:'openai'};
}

Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const{client,profile,user}=await authorisedProfile(req,['admin','district_partner']);const input=requestSchema.parse(await req.json());if(input.kind==='vendor_invoice'&&profile.role!=='admin')return json({error:'Only Admin can import vendor invoices.'},403);let files=input.files;const expanded=[] as typeof files;for(const f of files){if(f.name.toLowerCase().endsWith('.zip')){const zip=await JSZip.loadAsync(Uint8Array.from(atob(f.data),c=>c.charCodeAt(0)));for(const[name,item]of Object.entries(zip.files)){if(!item.dir&&/\.(pdf|png|jpe?g)$/i.test(name)){const bytes=await item.async('uint8array');let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));expanded.push({name,type:name.endsWith('.pdf')?'application/pdf':'image/jpeg',data:btoa(binary)});}}}else expanded.push(f);}files=expanded;if(!files.length)throw new Error('No supported document was found.');const total=files.reduce((s,f)=>s+f.data.length*0.75,0);if(total>30*1024*1024)throw new Error('Combined upload exceeds 30 MB.');
    const hashBytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(files.map(f=>`${f.name}:${f.data}`).join('|')));const fileHash=Array.from(new Uint8Array(hashBytes)).map(x=>x.toString(16).padStart(2,'0')).join('');
    const prompt=input.kind==='customer'?'Classify the supplied customer documents and extract only facts visibly present. Never infer a missing value. Use null and confidence 0 when absent. Source must name file and page. Masking is not required in structured output.':'Extract this vendor purchase invoice. Never invent values. Return every visible item row, totals, confidence and file/page evidence. fileHash must equal '+fileHash;
    const schema=input.kind==='customer'?customerJson:invoiceJson;const result=await extractWithGemini(prompt,files,schema)??await extractWithOpenAi(prompt,files,schema,`${input.kind}_extraction`);if(!result)throw new Error('No AI provider is configured. Set GEMINI_API_KEY (recommended) or OPENAI_API_KEY in Supabase Edge Function secrets.');const extraction=result.extraction;if(input.kind==='vendor_invoice')extraction.fileHash=fileHash;
    await client.from('ai_extraction_logs').insert({user_id:user.id,extraction_type:input.kind,file_hash:fileHash,file_names:files.map(f=>f.name),result:{...extraction,_provider:result.provider},status:'review_required'});return json({extraction,provider:result.provider});
  }catch(error){return json({error:error instanceof Error?error.message:'Document analysis failed.'},400);}});
