import { useEffect, useMemo, useState } from 'react';
import { BarChart3, Boxes, ChevronLeft, ChevronRight, FileText, FileUp, LayoutDashboard, LogOut, Menu, ReceiptText, Settings2, ShieldCheck, Users, X } from 'lucide-react';
import { Brand } from './components/Brand';
import { CrmProvider, useCrm } from './lib/CrmContext';
import { configurationError, supabase } from './lib/supabase';
import { hasSession, requestPasswordReset, signIn, signOut, updatePassword } from './services/repository';
import { Customers } from './features/Customers'; import { Dashboard } from './features/Dashboard'; import { Operations } from './features/Operations'; import { Projects } from './features/Projects'; import { Quotations } from './features/Quotations'; import { Pricing, Reports } from './features/ReportsPricing'; import { CustomerImporter } from './features/CustomerImporter'; import { Invoices } from './features/Invoices'; import { Inventory } from './features/Inventory'; import { Administration } from './features/Administration';
import type { Role } from './types/domain';

type Tab='dashboard'|'customers'|'importer'|'quotations'|'projects'|'invoices'|'inventory'|'operations'|'reports'|'pricing'|'administration';

type AuthScreen='loading'|'login'|'recovery'|'signup'|'workspace';

// Supabase invite/signup links land back on this app carrying `type=invite` (or `type=signup`)
// either as a query param or inside the URL hash, alongside the session tokens. The client
// auto-consumes those tokens and fires a plain SIGNED_IN event (not PASSWORD_RECOVERY), so
// without this check an invited user would be dropped straight into the workspace with no
// password ever set — the next time they try to log in normally, there is nothing to sign in
// with. We capture the link type once on first load and route those users to a set-password
// (sign up) screen instead, then clear it from the URL so a later refresh doesn't re-trigger it.
function detectLinkType(): 'invite' | 'recovery' | null {
  const search = new URLSearchParams(window.location.search);
  const hash = new URLSearchParams(window.location.hash.replace(/^#/, ''));
  const type = search.get('type') || hash.get('type');
  if (type === 'invite' || type === 'signup') return 'invite';
  if (type === 'recovery') return 'recovery';
  return null;
}

export default function App(){const[screen,setScreen]=useState<AuthScreen>('loading');const[linkType]=useState(detectLinkType);useEffect(()=>{if(configurationError){setScreen('login');return;}void hasSession().then((active)=>setScreen((current)=>current==='recovery'||current==='signup'?current:active?'workspace':'login'));const{data}=supabase!.auth.onAuthStateChange((event,s)=>{if(event==='PASSWORD_RECOVERY')setScreen('recovery');else if(event==='SIGNED_OUT')setScreen('login');else if(s&&['SIGNED_IN','TOKEN_REFRESHED','USER_UPDATED'].includes(event))setScreen((current)=>{if(current==='recovery'||current==='signup')return current;if(event==='SIGNED_IN'&&linkType==='invite')return 'signup';return 'workspace';});});return()=>data.subscription.unsubscribe();},[linkType]);const clearLinkParams=()=>{const url=new URL(window.location.href);url.search='';url.hash='';window.history.replaceState({},document.title,url.toString());};if(screen==='loading')return <div className="splash"><Brand/><span>Loading secure workspace...</span></div>;if(screen==='recovery')return <PasswordRecovery onComplete={()=>{clearLinkParams();setScreen('workspace');}}/>;if(screen==='signup')return <PasswordRecovery mode="signup" onComplete={()=>{clearLinkParams();setScreen('workspace');}}/>;if(screen==='login')return <Login onAuthenticated={()=>setScreen('workspace')}/>;return <CrmProvider><Workspace onLogout={async()=>{await signOut();setScreen('login');}}/></CrmProvider>;}

function PasswordRecovery({onComplete,mode='recovery'}:{onComplete:()=>void;mode?:'recovery'|'signup'}){const[password,setPassword]=useState('');const[confirm,setConfirm]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const isSignup=mode==='signup';return <main className="login-page"><section className="login-card"><Brand/><div><h1>{isSignup?'Complete Your Sign Up':'Create New Password'}</h1><p>{isSignup?'Your account was created by the Admin. Set a password to activate your Ratneswar Engineering login.':'Choose a strong password for your Ratneswar Engineering account.'}</p></div><form onSubmit={async(event)=>{event.preventDefault();if(password!==confirm){setError('Passwords do not match.');return;}setBusy(true);setError('');try{await updatePassword(password);onComplete();}catch(cause){setError(cause instanceof Error?cause.message:'Password update failed.');}finally{setBusy(false);}}}><label>New Password<input required type="password" minLength={12} autoComplete="new-password" value={password} onChange={(event)=>setPassword(event.target.value)}/></label><label>Confirm Password<input required type="password" minLength={12} autoComplete="new-password" value={confirm} onChange={(event)=>setConfirm(event.target.value)}/></label>{error&&<div className="alert alert--error">{error}</div>}<button className="btn btn--primary" disabled={busy}>{busy?'Saving...':isSignup?'Activate My Account':'Save New Password'}</button></form></section></main>;}

function Login({onAuthenticated}:{onAuthenticated:()=>void}) {
  const[email,setEmail]=useState(''); const[password,setPassword]=useState(''); const[error,setError]=useState(''); const[busy,setBusy]=useState(false); const[reset,setReset]=useState(false);
  const resetForm=<form onSubmit={async(e)=>{e.preventDefault();setBusy(true);setError('');try{await requestPasswordReset(email);setError('Password reset email sent. Check your inbox.');}catch(err){setError(err instanceof Error?err.message:'Unable to send reset email.');}finally{setBusy(false);}}}>
    <label>Email<input type="email" required value={email} onChange={(e)=>setEmail(e.target.value)}/></label>{error&&<div className="alert alert--info">{error}</div>}<button className="btn btn--primary" disabled={busy}>{busy?'Sending...':'Send Password Reset'}</button><button type="button" className="btn" onClick={()=>{setReset(false);setError('');}}>Back to Sign In</button></form>;
  const loginForm=<form onSubmit={async(e)=>{e.preventDefault();setBusy(true);setError('');try{await signIn(email,password);onAuthenticated();}catch(err){setError(err instanceof Error?err.message:'Login failed.');}finally{setBusy(false);}}}>
    <label>Email<input type="email" autoComplete="username" required value={email} onChange={(e)=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required minLength={12} value={password} onChange={(e)=>setPassword(e.target.value)}/></label>{error&&<div className="alert alert--error">{error}</div>}<button className="btn btn--primary" disabled={busy}>{busy?'Signing in...':'Sign In'}</button><button className="link-btn" type="button" onClick={()=>{setReset(true);setError('');}}>Forgot password?</button></form>;
  return <main className="login-page"><section className="login-card"><Brand/><div><h1>Solar EPC CRM</h1><p>Secure Ratneswar Engineering workspace</p></div>{configurationError?<div className="alert alert--error">{configurationError}</div>:reset?resetForm:loginForm}<small>Free secure sign-in with verified email, encrypted passwords, role permissions, database policies and automatic idle logout.</small></section></main>;
}

function Workspace({onLogout}:{onLogout:()=>Promise<void>}){const{data,loading,saving,error,refresh}=useCrm();const[tab,setTab]=useState<Tab>('dashboard');const[collapsed,setCollapsed]=useState(false);const[mobile,setMobile]=useState(false);useIdleLogout(onLogout,data?.settings.inactivityMinutes ?? 30);const allNav=useMemo(()=>[
  ['dashboard','Dashboard',LayoutDashboard],['customers','Customers',Users],['importer','AI Customer Import',FileUp],['quotations','Quotations',ReceiptText],['projects','Projects',Boxes],['invoices','Invoices',FileText],['inventory','Inventory',Boxes],['operations','Operations',Settings2],['reports','Reports',BarChart3],['pricing','Price List',ReceiptText],['administration','Administration',ShieldCheck],
] as const,[]);if(loading)return <div className="splash"><Brand compact/><span>Loading authorised records...</span></div>;if(!data)return <main className="login-page"><section className="login-card"><Brand/><div><h1>Workspace could not load</h1><p>Your login succeeded, but the authorised CRM profile or database setup is incomplete.</p></div><div className="alert alert--error">{error||'No active CRM profile was returned.'}</div><button className="btn btn--primary" onClick={()=>void refresh()}>Retry Loading</button><button className="btn" onClick={()=>void onLogout()}>Sign Out</button></section></main>;
  const allowed:Record<Role,Tab[]>={admin:['dashboard','customers','importer','quotations','projects','invoices','inventory','operations','reports','pricing','administration'],district_partner:['dashboard','customers','importer','quotations','projects','invoices','inventory','operations'],dealer:['dashboard','customers','quotations']};const nav=allNav.filter(([id])=>allowed[data.profile.role].includes(id));
  const roleLabel=data.profile.role==='district_partner'?'Area Partner':data.profile.role==='admin'?'Admin':'Dealer';
  return <div className={`app-shell operations-pro ${collapsed?'is-collapsed':''}`}><aside className={`sidebar ${mobile?'is-open':''}`}><div className="sidebar__brand"><Brand compact={!collapsed}/>{!collapsed&&<span>Solar CRM</span>}<button className="mobile-close" onClick={()=>setMobile(false)}><X size={18}/></button></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setMobile(false);}}><Icon size={19}/><span>{label}</span></button>)}</nav><div className="sidebar__footer"><div className="profile-chip"><div>{data.profile.fullName.charAt(0)}</div>{!collapsed&&<span><strong>{data.profile.fullName}</strong><small>{roleLabel}</small></span>}</div><button onClick={()=>void onLogout()} title="Sign out from this device"><LogOut size={18}/><span>Sign Out</span></button></div><button className="collapse-btn" onClick={()=>setCollapsed((v)=>!v)}>{collapsed?<ChevronRight size={17}/>:<ChevronLeft size={17}/>}</button></aside>{mobile&&<button aria-label="Close navigation" className="mobile-overlay" onClick={()=>setMobile(false)}/>}<div className="main-shell"><header className="topbar"><button className="menu-btn" onClick={()=>setMobile(true)}><Menu size={20}/></button><div><strong>{data.settings.company.tradeName}</strong><span>GSTIN {data.settings.company.gstin}</span></div><div className="sync-state"><i className={saving?'saving':'saved'}/>{saving?'Saving...':'Cloud Synced'}</div></header>{error&&<div className="global-error">{error}</div>}<main className="content">{tab==='dashboard'&&<Dashboard onNavigate={(target)=>setTab(target)}/>} {tab==='customers'&&<Customers/>}{tab==='importer'&&<CustomerImporter/>}{tab==='quotations'&&<Quotations/>}{tab==='projects'&&<Projects/>}{tab==='invoices'&&<Invoices/>}{tab==='inventory'&&<Inventory/>}{tab==='operations'&&<Operations/>}{tab==='reports'&&<Reports/>}{tab==='pricing'&&<Pricing/>}{tab==='administration'&&<Administration/>}</main></div></div>;
}

function useIdleLogout(onLogout:()=>Promise<void>,minutes:number){useEffect(()=>{let timer:number;const reset=()=>{window.clearTimeout(timer);timer=window.setTimeout(()=>void onLogout(),minutes*60_000);};const events=['pointerdown','keydown','scroll','touchstart'];events.forEach((e)=>window.addEventListener(e,reset,{passive:true}));reset();return()=>{window.clearTimeout(timer);events.forEach((e)=>window.removeEventListener(e,reset));};},[minutes,onLogout]);}
