begin;

create or replace function public.save_quotation_version(p_quote jsonb) returns uuid language plpgsql security definer set search_path=public as $$
declare qid uuid; qno text; ver int; old_status quote_status; cid uuid:=(p_quote->>'customerId')::uuid; c customers%rowtype; price active_price_rows%rowtype; final numeric:=(p_quote->>'grandTotal')::numeric; suggested numeric; v_id uuid:=gen_random_uuid(); item jsonb; actor uuid:=auth.uid(); dealer uuid; commission numeric:=0;
begin if not can_access_customer(cid) then raise exception 'Customer is not accessible'; end if; select * into c from customers where id=cid;
 if public.current_role()='dealer' then dealer:=current_dealer(); else dealer:=nullif(p_quote->>'dealerId','')::uuid; end if;
 select * into price from active_price_rows where panel_brand=upper(p_quote->>'panelBrand') and panel_technology=p_quote->>'panelTechnology' and panel_wattage=(p_quote->>'panelWattage')::int and panel_quantity=(p_quote->>'panelQuantity')::int;
 if price.id is null then raise exception 'No exact active price configuration exists'; end if; suggested:=price.gross_price;
 if final<>suggested and nullif(trim(p_quote->>'priceOverrideReason'),'') is null then raise exception 'Price override reason is required'; end if;
 if (p_quote->>'taxMode')<>'inclusive' then raise exception 'Published price is GST-inclusive and cannot be changed to GST-extra'; end if;
 if public.current_role()='dealer' then commission:=0; else commission:=coalesce(nullif(p_quote->>'dealerCommission','')::numeric,0); end if;
 if nullif(p_quote->>'quoteNo','') is not null then select id,quotation_no,current_version+1,current_status into qid,qno,ver,old_status from quotations where quotation_no=p_quote->>'quoteNo' and deleted_at is null; end if;
 if qid is null then qid:=coalesce(nullif(p_quote->>'id','')::uuid,gen_random_uuid());qno:=next_document_number('quotation','QT');ver:=1;insert into quotations(id,quotation_no,customer_id,district_id,dealer_id,current_version,current_status,created_by,updated_by) values(qid,qno,cid,c.district_id,dealer,ver,'draft',actor,actor);insert into quotation_status_history(quotation_id,to_status,changed_by) values(qid,'draft',actor);
 else update quotations set current_version=ver,current_status='draft',dealer_id=dealer,updated_by=actor,updated_at=now(),sent_at=null,approved_at=null,rejected_at=null where id=qid; insert into quotation_status_history(quotation_id,from_status,to_status,reason,changed_by) values(qid,old_status,'draft','Commercial revision created',actor); end if;
 insert into quotation_versions(id,quotation_id,version_no,price_list_item_id,system_type,dcr_type,scheme,panel_brand,panel_technology,panel_wattage,panel_quantity,dc_capacity_kw,suggested_price,final_price,price_override_reason,gst_included,dealer_commission,internal_cost,immutable_snapshot,created_by)
 values(v_id,qid,ver,price.id,p_quote->>'systemType',p_quote->>'dcrType',p_quote->>'scheme',upper(p_quote->>'panelBrand'),p_quote->>'panelTechnology',(p_quote->>'panelWattage')::int,(p_quote->>'panelQuantity')::int,price.dc_capacity_kw,suggested,final,nullif(p_quote->>'priceOverrideReason',''),true,commission,case when public.current_role()='dealer' then 0 else coalesce(nullif(p_quote->>'internalCost','')::numeric,0) end,p_quote||jsonb_build_object('id',qid,'quoteNo',qno,'versionNo',ver,'status','draft','suggestedPrice',suggested,'basePrice',final,'grandTotal',final,'dcCapacityKw',price.dc_capacity_kw,'dealerId',dealer,'dealerCommission',commission,'taxMode','inclusive'),actor);
 for item in select * from jsonb_array_elements(coalesce(p_quote->'items','[]')) loop insert into quotation_items(quotation_version_id,description,brand,specification,quantity,unit,rate,selected,internal_only) values(v_id,item->>'description',nullif(item->>'brand',''),nullif(item->>'specification',''),coalesce((item->>'quantity')::numeric,1),coalesce(item->>'unit','Nos'),coalesce(nullif(item->>'rate','')::numeric,0),coalesce((item->>'selected')::boolean,true),coalesce((item->>'internalOnly')::boolean,false)); end loop;
 if final<>suggested then insert into quotation_overrides(quotation_id,version_no,suggested_price,final_price,reason,created_by) values(qid,ver,suggested,final,p_quote->>'priceOverrideReason',actor); end if;
 insert into audit_logs(actor_id,action,entity_type,entity_id,reason,metadata) values(actor,'quotation_version_saved','quotation',qid,nullif(p_quote->>'priceOverrideReason',''),jsonb_build_object('version',ver,'suggested',suggested,'final',final)); return qid; end $$;
grant execute on function public.save_quotation_version(jsonb) to authenticated;

create or replace function public.set_quotation_status(p_quotation_id uuid,p_status quote_status,p_reason text default null) returns void language plpgsql security definer set search_path=public as $$
declare q quotations%rowtype; old quote_status; role app_role:=public.current_role();
begin select * into q from quotations where id=p_quotation_id and deleted_at is null for update; if not can_access_customer(q.customer_id) then raise exception 'Not authorised'; end if; old:=q.current_status;
 if role='dealer' and not(old='draft' and p_status='sent') then raise exception 'Dealer can only send a draft quotation'; end if;
 if role in('admin','district_partner') and not((old='draft' and p_status in('sent','rejected')) or (old in('sent','pending') and p_status in('pending','approved','rejected'))) then raise exception 'Invalid quotation status transition'; end if;
 if p_status='rejected' and nullif(trim(p_reason),'') is null then raise exception 'Rejection reason is required'; end if;
 update quotations set current_status=p_status,updated_by=auth.uid(),updated_at=now(),sent_at=case when p_status='sent' then now() else sent_at end,approved_at=case when p_status='approved' then now() else approved_at end,rejected_at=case when p_status='rejected' then now() else rejected_at end where id=p_quotation_id;
 insert into quotation_status_history(quotation_id,from_status,to_status,reason,changed_by) values(p_quotation_id,old,p_status,p_reason,auth.uid()); insert into audit_logs(actor_id,action,entity_type,entity_id,reason,metadata) values(auth.uid(),'quotation_status_changed','quotation',p_quotation_id,p_reason,jsonb_build_object('from',old,'to',p_status)); end $$;
grant execute on function public.set_quotation_status(uuid,quote_status,text) to authenticated;

create or replace function public.can_transition(p_from project_stage,p_to project_stage) returns boolean language sql immutable as $$select case p_from when 'project_created' then p_to='planning_done' when 'planning_done' then p_to in('loan_required','loan_not_required') when 'loan_required' then p_to='loan_application_pending' when 'loan_application_pending' then p_to='loan_applied' when 'loan_applied' then p_to in('loan_sanctioned','loan_rejected') when 'loan_rejected' then p_to in('loan_application_pending','documentation_pending') when 'loan_sanctioned' then p_to='documentation_pending' when 'loan_not_required' then p_to='documentation_pending' when 'documentation_pending' then p_to='documentation_completed' when 'documentation_completed' then p_to='material_requirement_generated' when 'material_requirement_generated' then p_to='material_reserved' when 'material_reserved' then p_to='material_dispatched' when 'material_dispatched' then p_to='installation_in_progress' when 'installation_in_progress' then p_to='installation_done' when 'installation_done' then p_to='inspection_pending' when 'inspection_pending' then p_to='inspection_done' when 'inspection_done' then p_to='meter_pending' when 'meter_pending' then p_to='meter_done' when 'meter_done' then p_to='commissioning_done' when 'commissioning_done' then p_to in('subsidy_pending','handover_completed') when 'subsidy_pending' then p_to='subsidy_passed' when 'subsidy_passed' then p_to='handover_completed' when 'handover_completed' then p_to='project_closed' else false end$$;

create or replace function public.generate_agreement_and_project(p_quotation_id uuid,p_signature_path text,p_generated_file_path text,p_agreement_date date) returns uuid language plpgsql security definer set search_path=public as $$
declare q quotations%rowtype; v quotation_versions%rowtype; c customers%rowtype; aid uuid:=gen_random_uuid(); pid uuid:=gen_random_uuid(); req record; inv record; available numeric; reserve_qty numeric;
begin if public.current_role() not in('admin','district_partner') then raise exception 'Not authorised'; end if; select * into q from quotations where id=p_quotation_id for update; if q.id is null or q.current_status<>'approved' or not can_access_customer(q.customer_id) then raise exception 'Accessible approved quotation required'; end if; if exists(select 1 from projects where quotation_id=q.id) then raise exception 'A project already exists for this quotation'; end if; if nullif(p_generated_file_path,'') is null or nullif(p_signature_path,'') is null then raise exception 'Generated agreement and customer signature are required'; end if; select * into v from quotation_versions where quotation_id=q.id and version_no=q.current_version; select * into c from customers where id=q.customer_id;
 insert into agreements(id,agreement_no,customer_id,quotation_id,agreement_date,status,capacity_kw,gross_price,signature_path,generated_file_path,snapshot,generated_by) values(aid,next_document_number('agreement','AG'),q.customer_id,q.id,p_agreement_date,'generated',v.dc_capacity_kw,v.final_price,p_signature_path,p_generated_file_path,v.immutable_snapshot,auth.uid());
 insert into projects(id,project_no,customer_id,quotation_id,agreement_id,district_id,dealer_id,current_stage,accepted_quotation_snapshot,assigned_partner_id,created_by) values(pid,next_document_number('project','PR'),q.customer_id,q.id,aid,q.district_id,q.dealer_id,'project_created',v.immutable_snapshot,c.assigned_partner_id,auth.uid()); update agreements set project_id=pid where id=aid; update quotations set current_status='project_created',project_created_at=now(),updated_by=auth.uid(),updated_at=now() where id=q.id; insert into quotation_status_history(quotation_id,from_status,to_status,reason,changed_by) values(q.id,'approved','project_created','Agreement generated',auth.uid()); insert into project_stage_history(project_id,to_stage,note,changed_by) values(pid,'project_created','Agreement generated and accepted quotation snapshot locked',auth.uid());
 insert into project_material_requirements(project_id,item_code,item_name,specification,required_qty,unit) values(pid,format('PV-%s-%s',v.panel_brand,v.panel_wattage),format('%s %s Solar Panel',v.panel_brand,v.panel_technology),format('%s Wp',v.panel_wattage),v.panel_quantity,'Nos');
 insert into project_material_requirements(project_id,item_code,item_name,specification,required_qty,unit) select pid,upper(left(regexp_replace(qi.description,'[^A-Za-z0-9]+','-','g'),30)),qi.description,concat_ws(' - ',qi.brand,qi.specification),qi.quantity,qi.unit from quotation_items qi where qi.quotation_version_id=v.id and qi.selected and not qi.internal_only and lower(qi.description) not like '%pv module%';
 for req in select * from project_material_requirements where project_id=pid loop select i.*,b.available into inv from inventory_items i join inventory_balance b on b.id=i.id where i.item_code=req.item_code and (i.district_id is null or i.district_id=q.district_id) limit 1; if inv.id is not null then reserve_qty:=least(req.required_qty,greatest(inv.available,0)); update project_material_requirements set inventory_item_id=inv.id,reserved_qty=reserve_qty where id=req.id; if reserve_qty>0 then insert into stock_transactions(inventory_item_id,transaction_type,quantity,project_id,reference_no,reason,idempotency_key,created_by) values(inv.id,'reservation',reserve_qty,pid,q.quotation_no,'Automatic project reservation',format('project:%s:reserve:%s',pid,req.id),auth.uid()); end if; end if; end loop;
 if q.dealer_id is not null and v.dealer_commission>0 then insert into dealer_commissions(dealer_id,customer_id,project_id,quotation_id,commission_type,commission_value,total_commission,created_by) values(q.dealer_id,q.customer_id,pid,q.id,'fixed',v.dealer_commission,v.dealer_commission,auth.uid()); end if;
 insert into audit_logs(actor_id,action,entity_type,entity_id,metadata) values(auth.uid(),'agreement_generated_project_created','project',pid,jsonb_build_object('agreementId',aid,'quotationId',q.id)); return pid; end $$;
grant execute on function public.generate_agreement_and_project(uuid,text,text,date) to authenticated;

create or replace function public.change_project_stage(p_project_id uuid,p_new_stage project_stage,p_note text default null,p_override_reason text default null) returns void language plpgsql security definer set search_path=public as $$
declare p projects%rowtype; valid boolean;
begin select * into p from projects where id=p_project_id for update; if p.id is null or not can_access_project(p.id) or public.current_role()='dealer' then raise exception 'Not authorised'; end if; valid:=can_transition(p.current_stage,p_new_stage); if not valid and (not is_admin() or nullif(trim(p_override_reason),'') is null) then raise exception 'Invalid stage transition'; end if; if nullif(trim(p_note),'') is null then raise exception 'Stage note is required'; end if;
 update projects set current_stage=p_new_stage,updated_at=now(),row_version=row_version+1,closed_at=case when p_new_stage='project_closed' then now() else closed_at end where id=p.id; insert into project_stage_history(project_id,from_stage,to_stage,note,override_reason,changed_by) values(p.id,p.current_stage,p_new_stage,p_note,p_override_reason,auth.uid());
 if p_new_stage='material_dispatched' then insert into stock_transactions(inventory_item_id,transaction_type,quantity,project_id,reference_no,reason,idempotency_key,created_by) select inventory_item_id,'issue',reserved_qty,p.id,p.project_no,'Reserved material dispatched',format('project:%s:issue:%s',p.id,id),auth.uid() from project_material_requirements where project_id=p.id and inventory_item_id is not null and reserved_qty>0 and issued_qty=0 on conflict(idempotency_key) do nothing; update project_material_requirements set issued_qty=reserved_qty where project_id=p.id and reserved_qty>0; end if;
 insert into audit_logs(actor_id,action,entity_type,entity_id,reason,metadata) values(auth.uid(),'project_stage_changed','project',p.id,p_override_reason,jsonb_build_object('from',p.current_stage,'to',p_new_stage,'note',p_note)); end $$;
grant execute on function public.change_project_stage(uuid,project_stage,text,text) to authenticated;

create or replace function public.post_stock_transaction(p_transaction jsonb) returns uuid language plpgsql security definer set search_path=public as $$
declare tid uuid:=coalesce(nullif(p_transaction->>'id','')::uuid,gen_random_uuid()); iid uuid:=(p_transaction->>'inventoryItemId')::uuid; typ stock_transaction_type:=(p_transaction->>'transactionType')::stock_transaction_type; qty numeric:=(p_transaction->>'quantity')::numeric; bal inventory_balance%rowtype;
begin if not is_admin() then raise exception 'Admin access required'; end if; if typ in('reservation','issue','consumption') then raise exception 'Project stock transactions must use the project workflow'; end if; if typ in('damage','adjustment') and nullif(trim(p_transaction->>'reason'),'') is null then raise exception 'Adjustment reason is required'; end if; select * into bal from inventory_balance where id=iid; if typ='damage' and coalesce(bal.on_hand,0)<qty then raise exception 'Negative stock is not allowed'; end if;
 insert into stock_transactions(id,inventory_item_id,transaction_type,quantity,project_id,unit_rate,reference_no,reason,idempotency_key,occurred_at,created_by) values(tid,iid,typ,qty,nullif(p_transaction->>'projectId','')::uuid,nullif(p_transaction->>'unitRate','')::numeric,nullif(p_transaction->>'referenceNo',''),nullif(p_transaction->>'reason',''),p_transaction->>'idempotencyKey',coalesce(nullif(p_transaction->>'occurredAt','')::timestamptz,now()),auth.uid()); insert into audit_logs(actor_id,action,entity_type,entity_id,reason,metadata) values(auth.uid(),'stock_transaction_posted','inventory_item',iid,p_transaction->>'reason',jsonb_build_object('type',typ,'quantity',qty,'transactionId',tid)); return tid; end $$;
grant execute on function public.post_stock_transaction(jsonb) to authenticated;

create or replace function public.create_inventory_item(p_item jsonb) returns uuid language plpgsql security definer set search_path=public as $$
declare iid uuid:=gen_random_uuid();did uuid;
begin if not is_admin() then raise exception 'Admin access required'; end if; did:=nullif(p_item->>'districtId','')::uuid; insert into inventory_items(id,item_code,item_name,category,brand,model,specification,unit,district_id,serialized,reorder_level,created_by) values(iid,upper(trim(p_item->>'itemCode')),trim(p_item->>'itemName'),p_item->>'category',nullif(p_item->>'brand',''),nullif(p_item->>'model',''),nullif(p_item->>'specification',''),p_item->>'unit',did,coalesce((p_item->>'serialized')::boolean,false),coalesce(nullif(p_item->>'reorderLevel','')::numeric,0),auth.uid());insert into audit_logs(actor_id,action,entity_type,entity_id,metadata) values(auth.uid(),'inventory_item_created','inventory_item',iid,p_item);return iid;end $$;
grant execute on function public.create_inventory_item(jsonb) to authenticated;

create or replace function public.post_purchase_invoice(p_invoice jsonb) returns uuid language plpgsql security definer set search_path=public as $$
declare iid uuid:=gen_random_uuid(); row jsonb; line_total numeric:=0; item_id uuid; idx int:=0; qty numeric;
begin if not is_admin() then raise exception 'Admin access required'; end if; for row in select * from jsonb_array_elements(coalesce(p_invoice->'rows','[]')) loop line_total:=line_total+coalesce((row->>'total')::numeric,0); if nullif(row->>'inventoryItemId','') is null then raise exception 'Every invoice row must be mapped to an inventory item'; end if; end loop; if abs(line_total-(p_invoice->>'total')::numeric)>1 then raise exception 'Invoice row totals do not match the invoice total'; end if;
 insert into purchase_invoices(id,vendor_name,vendor_gstin,invoice_number,invoice_date,gross_total,file_hash,storage_path,snapshot,created_by) values(iid,p_invoice->>'vendorName',nullif(p_invoice->>'gstin',''),p_invoice->>'invoiceNumber',(p_invoice->>'invoiceDate')::date,(p_invoice->>'total')::numeric,p_invoice->>'fileHash',nullif(p_invoice->>'storagePath',''),p_invoice,auth.uid());
 for row in select * from jsonb_array_elements(p_invoice->'rows') loop idx:=idx+1;item_id:=(row->>'inventoryItemId')::uuid;qty:=(row->>'quantity')::numeric;insert into purchase_invoice_items(purchase_invoice_id,inventory_item_id,description,brand,model,hsn_sac,quantity,unit,rate,tax_rate,total,serial_numbers) values(iid,item_id,row->>'description',nullif(row->>'brand',''),nullif(row->>'model',''),nullif(row->>'hsn',''),qty,row->>'unit',(row->>'rate')::numeric,(row->>'tax')::numeric,(row->>'total')::numeric,coalesce(array(select jsonb_array_elements_text(row->'serialNumbers')),'{}'));insert into stock_transactions(inventory_item_id,transaction_type,quantity,purchase_invoice_id,unit_rate,tax_details,reference_no,idempotency_key,created_by) values(item_id,'purchase',qty,iid,(row->>'rate')::numeric,jsonb_build_object('rate',row->>'tax'),p_invoice->>'invoiceNumber',format('purchase:%s:%s',iid,idx),auth.uid()); end loop;
 insert into audit_logs(actor_id,action,entity_type,entity_id,metadata) values(auth.uid(),'purchase_invoice_posted','purchase_invoice',iid,jsonb_build_object('total',p_invoice->>'total','rows',idx)); return iid;
exception when unique_violation then raise exception 'Duplicate vendor invoice number or file upload'; end $$;
grant execute on function public.post_purchase_invoice(jsonb) to authenticated;

create or replace function public.pay_dealer_commission(p_payment jsonb) returns uuid language plpgsql security definer set search_path=public as $$
declare pid uuid:=coalesce(nullif(p_payment->>'id','')::uuid,gen_random_uuid()); c dealer_commissions%rowtype; amount numeric:=(p_payment->>'amount')::numeric;
begin if not is_admin() then raise exception 'Admin access required'; end if; select * into c from dealer_commissions where id=(p_payment->>'commissionId')::uuid for update; if c.id is null or amount<=0 or c.amount_paid+amount>c.total_commission then raise exception 'Payment exceeds outstanding commission'; end if; insert into dealer_commission_payments(id,commission_id,payment_date,amount,mode,reference_no,notes,created_by) values(pid,c.id,(p_payment->>'paymentDate')::date,amount,p_payment->>'mode',nullif(p_payment->>'referenceNo',''),nullif(p_payment->>'notes',''),auth.uid()); update dealer_commissions set amount_paid=amount_paid+amount,status=case when amount_paid+amount=total_commission then 'paid' else 'partial' end,updated_at=now() where id=c.id; insert into audit_logs(actor_id,action,entity_type,entity_id,metadata) values(auth.uid(),'dealer_commission_paid','dealer_commission',c.id,jsonb_build_object('amount',amount,'paymentId',pid)); return pid; end $$;
grant execute on function public.pay_dealer_commission(jsonb) to authenticated;

create or replace function public.save_installation_and_issue_invoice(p_project_id uuid,p_details jsonb) returns uuid language plpgsql security definer set search_path=public as $$
declare p projects%rowtype; q jsonb; expected int; serial_count int; duplicate_count int; tr tax_rules%rowtype; gross numeric; taxable numeric; tax numeric; inv_id uuid:=gen_random_uuid(); inv_no text; serial text; panel_item uuid;
begin select * into p from projects where id=p_project_id for update; if p.id is null or not can_access_project(p.id) or public.current_role()='dealer' then raise exception 'Not authorised'; end if; if p.current_stage<>'installation_done' then raise exception 'Invoice is available only after Project Installation Done'; end if; if exists(select 1 from customer_invoices where project_id=p.id and status in('issued','paid')) then raise exception 'An active invoice already exists'; end if; q:=p.accepted_quotation_snapshot;expected:=(q->>'panelQuantity')::int;serial_count:=jsonb_array_length(coalesce(p_details->'panelSerials','[]'));if serial_count<1 then raise exception 'Panel serial numbers are required'; end if;select count(*)-count(distinct value) into duplicate_count from jsonb_array_elements_text(p_details->'panelSerials');if duplicate_count>0 then raise exception 'Duplicate panel serial numbers are not allowed'; end if;if (serial_count<>expected or p_details->>'panelBrand'<>q->>'panelBrand' or (p_details->>'panelWattage')::int<>(q->>'panelWattage')::int) and nullif(trim(p_details->>'overrideReason'),'') is null then raise exception 'Material change reason is required'; end if;
 select inventory_item_id into panel_item from project_material_requirements where project_id=p.id and item_code like 'PV-%' limit 1; if panel_item is null then insert into inventory_items(item_code,item_name,category,brand,model,specification,unit,district_id,serialized,reorder_level,created_by) values(format('PV-%s-%s',p_details->>'panelBrand',p_details->>'panelWattage'),format('%s %s Solar Panel',p_details->>'panelBrand',p_details->>'panelTechnology'),'PV Module',p_details->>'panelBrand',p_details->>'panelTechnology',format('%s Wp',p_details->>'panelWattage'),'Nos',p.district_id,true,0,auth.uid()) on conflict(item_code) do update set item_name=excluded.item_name returning id into panel_item; update project_material_requirements set inventory_item_id=panel_item where project_id=p.id and item_code like 'PV-%'; end if;
 for serial in select jsonb_array_elements_text(p_details->'panelSerials') loop if exists(select 1 from inventory_serials where serial_number=serial) then raise exception 'Installed serial number % already exists',serial; end if; insert into inventory_serials(inventory_item_id,serial_number,status,project_id) values(panel_item,serial,'installed',p.id); end loop;
 insert into installation_materials(project_id,details,created_by) values(p.id,p_details,auth.uid()); select * into tr from tax_rules where active and effective_from<=current_date and (effective_to is null or effective_to>=current_date) order by effective_from desc limit 1; if tr.id is null then raise exception 'No active effective-dated tax rule exists'; end if;gross:=(q->>'grandTotal')::numeric;taxable:=round(gross*100/(100+tr.gst_rate),2);tax:=gross-taxable;inv_no:=next_document_number('invoice','INV');
 insert into customer_invoices(id,invoice_no,customer_id,project_id,invoice_date,place_of_supply,status,tax_rule_id,taxable_value,cgst,sgst,igst,grand_total,snapshot,issued_by) values(inv_id,inv_no,p.customer_id,p.id,current_date,'Gujarat (24)','issued',tr.id,taxable,case when tr.intrastate then round(tax/2,2) else 0 end,case when tr.intrastate then tax-round(tax/2,2) else 0 end,case when tr.intrastate then 0 else tax end,gross,jsonb_build_object('id',inv_id,'invoiceNo',inv_no,'customerId',p.customer_id,'projectId',p.id,'invoiceDate',current_date,'placeOfSupply','Gujarat (24)','status','issued','taxMode','inclusive','taxableValue',taxable,'cgst',case when tr.intrastate then round(tax/2,2) else 0 end,'sgst',case when tr.intrastate then tax-round(tax/2,2) else 0 end,'igst',case when tr.intrastate then 0 else tax end,'roundOff',0,'grandTotal',gross),auth.uid());
 insert into customer_invoice_items(invoice_id,description,hsn_sac,quantity,unit,taxable_value,tax_rate,serial_numbers) values(inv_id,format('Supply and Installation of %s kW Rooftop Solar Power Plant',q->>'dcCapacityKw'),'8541 / 9954',1,'Job',taxable,tr.gst_rate,array(select jsonb_array_elements_text(p_details->'panelSerials'))); insert into audit_logs(actor_id,action,entity_type,entity_id,reason,metadata) values(auth.uid(),'customer_invoice_issued','customer_invoice',inv_id,p_details->>'overrideReason',jsonb_build_object('projectId',p.id,'gross',gross,'serialCount',serial_count)); return inv_id; end $$;
grant execute on function public.save_installation_and_issue_invoice(uuid,jsonb) to authenticated;

-- RLS: deny by default, then grant the minimum scoped access needed by the application.
do $$declare t text;begin foreach t in array array['districts','profiles','dealers','document_counters','customers','customer_documents','site_surveys','price_lists','price_list_items','inverter_products','subsidy_rules','tax_rules','quotations','quotation_versions','quotation_items','quotation_status_history','quotation_overrides','agreements','agreement_signatures','projects','project_stage_history','project_documents','project_material_requirements','installation_materials','inventory_items','inventory_serials','stock_transactions','purchase_invoices','purchase_invoice_items','dealer_commissions','dealer_commission_payments','customer_invoices','customer_invoice_items','payments','expenses','company_settings','audit_logs','ai_extraction_logs'] loop execute format('alter table public.%I enable row level security',t);end loop;end$$;
create policy districts_read on districts for select to authenticated using(active or is_admin());
create policy districts_admin on districts for all to authenticated using(is_admin()) with check(is_admin());
create policy profiles_read on profiles for select to authenticated using(id=auth.uid() or is_admin());
create policy profiles_admin on profiles for all to authenticated using(is_admin()) with check(is_admin());
create policy dealers_read on dealers for select to authenticated using(is_admin() or (public.current_role()='district_partner' and district_id=current_district()) or id=current_dealer());
create policy customers_read on customers for select to authenticated using(can_access_customer(id));
create policy customer_documents_access on customer_documents for select to authenticated using(can_access_customer(customer_id));
create policy customer_documents_insert on customer_documents for insert to authenticated with check(can_access_customer(customer_id));
create policy surveys_access on site_surveys for all to authenticated using(can_access_customer(customer_id)) with check(can_access_customer(customer_id));
create policy price_lists_read on price_lists for select to authenticated using(true);create policy price_items_read on price_list_items for select to authenticated using(true);create policy inverters_read on inverter_products for select to authenticated using(true);create policy subsidy_read on subsidy_rules for select to authenticated using(true);create policy tax_read on tax_rules for select to authenticated using(public.current_role() in('admin','district_partner'));
create policy subsidy_admin_write on subsidy_rules for insert to authenticated with check(is_admin());create policy tax_admin_write on tax_rules for insert to authenticated with check(is_admin());
create policy quotations_read on quotations for select to authenticated using(can_access_customer(customer_id));
create policy quote_versions_read on quotation_versions for select to authenticated using(exists(select 1 from quotations q where q.id=quotation_id and can_access_customer(q.customer_id)));
create policy quote_items_read on quotation_items for select to authenticated using(exists(select 1 from quotation_versions v join quotations q on q.id=v.quotation_id where v.id=quotation_version_id and can_access_customer(q.customer_id)));
create policy quote_history_read on quotation_status_history for select to authenticated using(exists(select 1 from quotations q where q.id=quotation_id and can_access_customer(q.customer_id)));
create policy quote_override_internal on quotation_overrides for select to authenticated using(public.current_role() in('admin','district_partner') and exists(select 1 from quotations q where q.id=quotation_id and can_access_customer(q.customer_id)));
create policy agreements_read on agreements for select to authenticated using(public.current_role() in('admin','district_partner') and can_access_customer(customer_id));
create policy agreement_signatures_read on agreement_signatures for select to authenticated using(exists(select 1 from agreements a where a.id=agreement_id and public.current_role() in('admin','district_partner') and can_access_customer(a.customer_id)));
create policy projects_read on projects for select to authenticated using(can_access_project(id));
create policy project_history_read on project_stage_history for select to authenticated using(can_access_project(project_id));
create policy project_documents_read on project_documents for select to authenticated using(can_access_project(project_id));
create policy requirements_read on project_material_requirements for select to authenticated using(can_access_project(project_id));
create policy installation_read on installation_materials for select to authenticated using(can_access_project(project_id));
create policy inventory_read on inventory_items for select to authenticated using(is_admin() or (public.current_role()='district_partner' and (district_id is null or district_id=current_district())));
create policy inventory_serials_read on inventory_serials for select to authenticated using(is_admin() or exists(select 1 from inventory_items i where i.id=inventory_item_id and (i.district_id is null or i.district_id=current_district()) and public.current_role()='district_partner'));
create policy stock_read on stock_transactions for select to authenticated using(is_admin() or (public.current_role()='district_partner' and (can_access_project(project_id) or exists(select 1 from inventory_items i where i.id=inventory_item_id and i.district_id=current_district()))));
create policy purchase_admin_read on purchase_invoices for select to authenticated using(is_admin());create policy purchase_items_admin_read on purchase_invoice_items for select to authenticated using(is_admin());
create policy commissions_internal_read on dealer_commissions for select to authenticated using(is_admin() or (public.current_role()='district_partner' and exists(select 1 from projects p where p.id=project_id and p.district_id=current_district())));
create policy commission_payments_internal_read on dealer_commission_payments for select to authenticated using(is_admin() or (public.current_role()='district_partner' and exists(select 1 from dealer_commissions c join projects p on p.id=c.project_id where c.id=commission_id and p.district_id=current_district())));
create policy invoices_read on customer_invoices for select to authenticated using(public.current_role() in('admin','district_partner') and can_access_customer(customer_id));create policy invoice_items_read on customer_invoice_items for select to authenticated using(exists(select 1 from customer_invoices i where i.id=invoice_id and can_access_customer(i.customer_id) and public.current_role() in('admin','district_partner')));
create policy payments_read on payments for select to authenticated using(public.current_role() in('admin','district_partner') and can_access_customer(customer_id));create policy payments_insert on payments for insert to authenticated with check(public.current_role() in('admin','district_partner') and can_access_customer(customer_id));
create policy expenses_read on expenses for select to authenticated using(is_admin() or (public.current_role()='district_partner' and (project_id is null or can_access_project(project_id))));create policy expenses_insert on expenses for insert to authenticated with check(is_admin() or (public.current_role()='district_partner' and project_id is not null and can_access_project(project_id)));
create policy settings_admin on company_settings for all to authenticated using(is_admin()) with check(is_admin());
create policy audit_admin_read on audit_logs for select to authenticated using(is_admin());
create policy ai_logs_read on ai_extraction_logs for select to authenticated using(user_id=auth.uid() or is_admin());create policy ai_logs_insert on ai_extraction_logs for insert to authenticated with check(user_id=auth.uid());

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values
 ('customer-documents','customer-documents',false,15728640,array['application/pdf','image/jpeg','image/png']),('agreement-files','agreement-files',false,15728640,array['application/pdf','image/jpeg','image/png']),('project-files','project-files',false,15728640,array['application/pdf','image/jpeg','image/png']),('invoice-files','invoice-files',false,15728640,array['application/pdf']),('inventory-invoices','inventory-invoices',false,15728640,array['application/pdf','image/jpeg','image/png']) on conflict(id) do update set public=false;
create policy storage_customer_read on storage.objects for select to authenticated using(bucket_id='customer-documents' and can_access_customer((storage.foldername(name))[1]::uuid));
create policy storage_customer_insert on storage.objects for insert to authenticated with check(bucket_id='customer-documents' and can_access_customer((storage.foldername(name))[1]::uuid));
create policy storage_agreement_access on storage.objects for select to authenticated using(bucket_id='agreement-files' and public.current_role() in('admin','district_partner'));
create policy storage_agreement_insert on storage.objects for insert to authenticated with check(bucket_id='agreement-files' and public.current_role() in('admin','district_partner'));
create policy storage_project_access on storage.objects for select to authenticated using(bucket_id='project-files' and can_access_project((storage.foldername(name))[1]::uuid));
create policy storage_project_insert on storage.objects for insert to authenticated with check(bucket_id='project-files' and can_access_project((storage.foldername(name))[1]::uuid));
create policy storage_invoice_access on storage.objects for select to authenticated using(bucket_id='invoice-files' and public.current_role() in('admin','district_partner'));
create policy storage_inventory_admin on storage.objects for all to authenticated using(bucket_id='inventory-invoices' and is_admin()) with check(bucket_id='inventory-invoices' and is_admin());

grant select on all tables in schema public to authenticated;grant insert,update on public.site_surveys,public.customer_documents,public.payments,public.expenses,public.ai_extraction_logs,public.company_settings to authenticated;grant insert on public.tax_rules,public.subsidy_rules to authenticated;
revoke insert,update,delete on public.audit_logs,public.quotation_versions,public.quotation_status_history,public.stock_transactions,public.dealer_commission_payments,public.customer_invoices from authenticated;
commit;
